module.exports = {
	"metadata": {
		"dataVersion": "2",
		"matchId": "NA1_4425261717",
		"participants": [
			"Ga51IagRTh9cLFsgX1AM0xldfxPuH6iXdlvLk_cIDW8o3S2gwMHCQR3naxVx-EWISKei633in4qX2g",
			"CmvZCVRjJ2iAK9DeRWlPHU4DVSkvppQ29kc4G8QzXUqPAst8Md1KUJiWB9xxxyaXdosKqrEzQz6N7Q",
			"Q2EHjVk2eZKAl5XuGy_cWSMCIm7lLMW2OOzZqNxOF53NrU0hmeXOMfp6fRoSOiYYX1R3mmVF52X5BQ",
			"-rDTCsroAW3qIMgqJRusRss1Al7Hp5anU4D3dwGhldx5yZ4wLzfkAi2D1ZbvXQqayEpEnsnhJjaKZA",
			"D-RPIY7vKgxySENc4fSfN7KfBO82gAbK_zDNQ_K9JiEA89KBgHNJ1Hs0MV3TN_Ns1CTmJoUtbGgUQA",
			"bEi2StPDZEKf-uUqTicfkuUaSAs0HtHN-XCicQO8YfQGkOMl0pW3QRS6lZNUtCxOOwziKHtfhFc1JQ",
			"FOp274IqCSUu86Wxe3UXmxIH3DpihuXsFzFJJUoYfSEM7GzAPt3Lbxo8H1Lwi2E_zAFwGVKnkcd2_Q",
			"5gNuzOZXrH-LyqWmwtInxbuExHZv_WNBwPEs8GGf7Huf2JKlLT8J8IPB0PxI1TGOMRF-FDu52hrp5w",
			"HaRBje9KHYHSixzs9louvCODlRS0GsR0QChK2vChlTrbLVt-SEKC1Ksy3FhW6msgPco24YBmbxJqxw",
			"jVJIG4Dp8Rj8om8zo5KzNOzvBqzB4BW4X5pj7Y-_wnSPz480YCN_E1HRRvBk4ZSTUrR7GIvuqnNIkw"
		]
	},
	"info": {
		"gameCreation": 1662248502107,
		"gameDuration": 2134,
		"gameEndTimestamp": 1662250663542,
		"gameId": 4425261717,
		"gameMode": "CLASSIC",
		"gameName": "teambuilder-match-4425261717",
		"gameStartTimestamp": 1662248529089,
		"gameType": "MATCHED_GAME",
		"gameVersion": "12.16.462.4391",
		"mapId": 11,
		"participants": [
			{
				"assists": 10,
				"baronKills": 0,
				"basicPings": 11,
				"bountyLevel": 3,
				"challenges": {
					"12AssistStreakCount": 0,
					"abilityUses": 158,
					"acesBefore15Minutes": 0,
					"alliedJungleMonsterKills": 10.000000029802322,
					"baronBuffGoldAdvantageOverThreshold": 1,
					"baronTakedowns": 1,
					"blastConeOppositeOpponentCount": 0,
					"bountyGold": 825,
					"buffsStolen": 0,
					"completeSupportQuestInTime": 0,
					"controlWardsPlaced": 0,
					"damagePerMinute": 1107.94304510472,
					"damageTakenOnTeamPercentage": 0.22801246452322707,
					"dancedWithRiftHerald": 0,
					"deathsByEnemyChamps": 8,
					"dodgeSkillShotsSmallWindow": 8,
					"doubleAces": 0,
					"dragonTakedowns": 2,
					"earliestBaron": 1695.1561379032444,
					"earliestDragonTakedown": 929.0467466755875,
					"earlyLaningPhaseGoldExpAdvantage": 0,
					"effectiveHealAndShielding": 0,
					"elderDragonKillsWithOpposingSoul": 0,
					"elderDragonMultikills": 0,
					"enemyChampionImmobilizations": 73,
					"enemyJungleMonsterKills": 0,
					"epicMonsterKillsNearEnemyJungler": 0,
					"epicMonsterKillsWithin30SecondsOfSpawn": 0,
					"epicMonsterSteals": 0,
					"epicMonsterStolenWithoutSmite": 0,
					"firstTurretKilledTime": 663.4359872877812,
					"flawlessAces": 1,
					"fullTeamTakedown": 7,
					"gameLength": 2134.5152520014904,
					"getTakedownsInAllLanesEarlyJungleAsLaner": 0,
					"goldPerMinute": 502.47483324694053,
					"hadOpenNexus": 0,
					"immobilizeAndKillWithAlly": 12,
					"initialBuffCount": 0,
					"initialCrabCount": 0,
					"jungleCsBefore10Minutes": 0,
					"junglerTakedownsNearDamagedEpicMonster": 0,
					"kTurretsDestroyedBeforePlatesFall": 1,
					"kda": 2.75,
					"killAfterHiddenWithAlly": 1,
					"killParticipation": 0.3793103448275862,
					"killedChampTookFullTeamDamageSurvived": 0,
					"killingSprees": 2,
					"killsNearEnemyTurret": 1,
					"killsOnOtherLanesEarlyJungleAsLaner": 0,
					"killsOnRecentlyHealedByAramPack": 0,
					"killsUnderOwnTurret": 2,
					"killsWithHelpFromEpicMonster": 0,
					"knockEnemyIntoTeamAndKill": 11,
					"landSkillShotsEarlyGame": 0,
					"laneMinionsFirst10Minutes": 61,
					"laningPhaseGoldExpAdvantage": 0,
					"legendaryCount": 0,
					"lostAnInhibitor": 1,
					"maxCsAdvantageOnLaneOpponent": 28,
					"maxKillDeficit": 3,
					"maxLevelLeadLaneOpponent": 2,
					"moreEnemyJungleThanOpponent": -132.00000008940697,
					"multiKillOneSpell": 0,
					"multiTurretRiftHeraldCount": 0,
					"multikills": 3,
					"multikillsAfterAggressiveFlash": 1,
					"mythicItemUsed": 6631,
					"outerTurretExecutesBefore10Minutes": 0,
					"outnumberedKills": 4,
					"outnumberedNexusKill": 0,
					"perfectDragonSoulsTaken": 0,
					"perfectGame": 0,
					"pickKillWithAlly": 10,
					"playedChampSelectPosition": 1,
					"poroExplosions": 0,
					"quickCleanse": 0,
					"quickFirstTurret": 0,
					"quickSoloKills": 0,
					"riftHeraldTakedowns": 0,
					"saveAllyFromDeath": 0,
					"scuttleCrabKills": 1,
					"shortestTimeToAceFromFirstTakedown": 6.659964493982216,
					"skillshotsDodged": 75,
					"skillshotsHit": 0,
					"snowballsHit": 0,
					"soloBaronKills": 0,
					"soloKills": 3,
					"stealthWardsPlaced": 7,
					"survivedSingleDigitHpCount": 0,
					"survivedThreeImmobilizesInFight": 1,
					"takedownOnFirstTurret": 1,
					"takedowns": 22,
					"takedownsAfterGainingLevelAdvantage": 2,
					"takedownsBeforeJungleMinionSpawn": 0,
					"takedownsFirstXMinutes": 4,
					"takedownsInAlcove": 0,
					"takedownsInEnemyFountain": 0,
					"teamBaronKills": 2,
					"teamDamagePercentage": 0.24880694019877247,
					"teamElderDragonKills": 0,
					"teamRiftHeraldKills": 1,
					"threeWardsOneSweeperCount": 0,
					"tookLargeDamageSurvived": 0,
					"turretPlatesTaken": 5,
					"turretTakedowns": 4,
					"turretsTakenWithRiftHerald": 0,
					"twentyMinionsIn3SecondsCount": 0,
					"unseenRecalls": 0,
					"visionScoreAdvantageLaneOpponent": 0.2631455659866333,
					"visionScorePerMinute": 0.5261042218385396,
					"wardTakedowns": 4,
					"wardTakedownsBefore20M": 0,
					"wardsGuarded": 1
				},
				"champExperience": 20040,
				"champLevel": 18,
				"championId": 875,
				"championName": "Sett",
				"championTransform": 0,
				"consumablesPurchased": 3,
				"damageDealtToBuildings": 5114,
				"damageDealtToObjectives": 16624,
				"damageDealtToTurrets": 5114,
				"damageSelfMitigated": 45951,
				"deaths": 8,
				"detectorWardsPlaced": 0,
				"doubleKills": 2,
				"dragonKills": 0,
				"eligibleForProgression": true,
				"firstBloodAssist": false,
				"firstBloodKill": true,
				"firstTowerAssist": false,
				"firstTowerKill": true,
				"gameEndedInEarlySurrender": false,
				"gameEndedInSurrender": false,
				"goldEarned": 17875,
				"goldSpent": 16100,
				"individualPosition": "TOP",
				"inhibitorKills": 0,
				"inhibitorTakedowns": 1,
				"inhibitorsLost": 1,
				"item0": 3153,
				"item1": 6631,
				"item2": 3053,
				"item3": 3047,
				"item4": 6333,
				"item5": 3076,
				"item6": 3340,
				"itemsPurchased": 30,
				"killingSprees": 4,
				"kills": 12,
				"lane": "TOP",
				"largestCriticalStrike": 0,
				"largestKillingSpree": 3,
				"largestMultiKill": 3,
				"longestTimeSpentLiving": 581,
				"magicDamageDealt": 511,
				"magicDamageDealtToChampions": 484,
				"magicDamageTaken": 10896,
				"neutralMinionsKilled": 14,
				"nexusKills": 0,
				"nexusLost": 0,
				"nexusTakedowns": 0,
				"objectivesStolen": 0,
				"objectivesStolenAssists": 0,
				"participantId": 1,
				"pentaKills": 0,
				"perks": {
					"statPerks": {
						"defense": 5002,
						"flex": 5008,
						"offense": 5005
					},
					"styles": [
						{
							"description": "primaryStyle",
							"selections": [
								{
									"perk": 8008,
									"var1": 67,
									"var2": 6,
									"var3": 0
								},
								{
									"perk": 9111,
									"var1": 2072,
									"var2": 440,
									"var3": 0
								},
								{
									"perk": 9104,
									"var1": 15,
									"var2": 0,
									"var3": 0
								},
								{
									"perk": 8299,
									"var1": 1187,
									"var2": 0,
									"var3": 0
								}
							],
							"style": 8000
						},
						{
							"description": "subStyle",
							"selections": [
								{
									"perk": 8444,
									"var1": 1484,
									"var2": 0,
									"var3": 0
								},
								{
									"perk": 8242,
									"var1": 124,
									"var2": 0,
									"var3": 0
								}
							],
							"style": 8400
						}
					]
				},
				"physicalDamageDealt": 179016,
				"physicalDamageDealtToChampions": 26906,
				"physicalDamageTaken": 25993,
				"profileIcon": 3890,
				"puuid": "Ga51IagRTh9cLFsgX1AM0xldfxPuH6iXdlvLk_cIDW8o3S2gwMHCQR3naxVx-EWISKei633in4qX2g",
				"quadraKills": 0,
				"riotIdName": "",
				"riotIdTagline": "",
				"role": "SOLO",
				"sightWardsBoughtInGame": 0,
				"spell1Casts": 96,
				"spell2Casts": 16,
				"spell3Casts": 35,
				"spell4Casts": 11,
				"summoner1Casts": 6,
				"summoner1Id": 14,
				"summoner2Casts": 6,
				"summoner2Id": 4,
				"summonerId": "9gjTDwk8BIu9sQzkp0nujEMRWivRBP4Q_YMFdzW4-fEPr-d8",
				"summonerLevel": 600,
				"summonerName": "ZADDYAUSTIN",
				"teamEarlySurrendered": false,
				"teamId": 100,
				"teamPosition": "TOP",
				"timeCCingOthers": 31,
				"timePlayed": 2134,
				"totalDamageDealt": 217368,
				"totalDamageDealtToChampions": 39415,
				"totalDamageShieldedOnTeammates": 0,
				"totalDamageTaken": 42414,
				"totalHeal": 5446,
				"totalHealsOnTeammates": 0,
				"totalMinionsKilled": 224,
				"totalTimeCCDealt": 283,
				"totalTimeSpentDead": 301,
				"totalUnitsHealed": 1,
				"tripleKills": 1,
				"trueDamageDealt": 37840,
				"trueDamageDealtToChampions": 12023,
				"trueDamageTaken": 5524,
				"turretKills": 1,
				"turretTakedowns": 4,
				"turretsLost": 7,
				"unrealKills": 0,
				"visionScore": 18,
				"visionWardsBoughtInGame": 0,
				"wardsKilled": 4,
				"wardsPlaced": 7,
				"win": true
			},
			{
				"assists": 17,
				"baronKills": 1,
				"basicPings": 50,
				"bountyLevel": 1,
				"challenges": {
					"12AssistStreakCount": 0,
					"abilityUses": 251,
					"acesBefore15Minutes": 0,
					"alliedJungleMonsterKills": 110.10000026226044,
					"baronBuffGoldAdvantageOverThreshold": 1,
					"baronTakedowns": 1,
					"blastConeOppositeOpponentCount": 0,
					"bountyGold": 600,
					"buffsStolen": 0,
					"completeSupportQuestInTime": 0,
					"controlWardsPlaced": 0,
					"damagePerMinute": 917.0111368270202,
					"damageTakenOnTeamPercentage": 0.22422404054850723,
					"dancedWithRiftHerald": 0,
					"deathsByEnemyChamps": 11,
					"dodgeSkillShotsSmallWindow": 3,
					"doubleAces": 0,
					"dragonTakedowns": 1,
					"earliestBaron": 1695.1561379032444,
					"earliestDragonTakedown": 929.0467466755875,
					"earlyLaningPhaseGoldExpAdvantage": 0,
					"effectiveHealAndShielding": 0,
					"elderDragonKillsWithOpposingSoul": 0,
					"elderDragonMultikills": 0,
					"enemyChampionImmobilizations": 13,
					"enemyJungleMonsterKills": 0,
					"epicMonsterKillsNearEnemyJungler": 1,
					"epicMonsterKillsWithin30SecondsOfSpawn": 0,
					"epicMonsterSteals": 1,
					"epicMonsterStolenWithoutSmite": 1,
					"firstTurretKilledTime": 663.4359872877812,
					"flawlessAces": 1,
					"fullTeamTakedown": 7,
					"gameLength": 2134.5152520014904,
					"goldPerMinute": 494.4142904392155,
					"hadOpenNexus": 0,
					"immobilizeAndKillWithAlly": 10,
					"initialBuffCount": 2,
					"initialCrabCount": 1,
					"jungleCsBefore10Minutes": 61.00000008940697,
					"junglerKillsEarlyJungle": 0,
					"junglerTakedownsNearDamagedEpicMonster": 0,
					"kTurretsDestroyedBeforePlatesFall": 0,
					"kda": 2.909090909090909,
					"killAfterHiddenWithAlly": 1,
					"killParticipation": 0.5517241379310345,
					"killedChampTookFullTeamDamageSurvived": 0,
					"killingSprees": 2,
					"killsNearEnemyTurret": 2,
					"killsOnLanersEarlyJungleAsJungler": 3,
					"killsOnRecentlyHealedByAramPack": 0,
					"killsUnderOwnTurret": 1,
					"killsWithHelpFromEpicMonster": 0,
					"knockEnemyIntoTeamAndKill": 10,
					"landSkillShotsEarlyGame": 4,
					"laneMinionsFirst10Minutes": 5,
					"laningPhaseGoldExpAdvantage": 0,
					"legendaryCount": 0,
					"lostAnInhibitor": 1,
					"maxCsAdvantageOnLaneOpponent": 13.000000029802322,
					"maxKillDeficit": 3,
					"maxLevelLeadLaneOpponent": 2,
					"moreEnemyJungleThanOpponent": -71,
					"multiKillOneSpell": 0,
					"multiTurretRiftHeraldCount": 0,
					"multikills": 1,
					"multikillsAfterAggressiveFlash": 0,
					"mythicItemUsed": 3152,
					"outerTurretExecutesBefore10Minutes": 0,
					"outnumberedKills": 6,
					"outnumberedNexusKill": 0,
					"perfectDragonSoulsTaken": 0,
					"perfectGame": 0,
					"pickKillWithAlly": 21,
					"playedChampSelectPosition": 1,
					"poroExplosions": 0,
					"quickCleanse": 0,
					"quickFirstTurret": 0,
					"quickSoloKills": 0,
					"riftHeraldTakedowns": 1,
					"saveAllyFromDeath": 0,
					"scuttleCrabKills": 4,
					"shortestTimeToAceFromFirstTakedown": 6.659964493982216,
					"skillshotsDodged": 56,
					"skillshotsHit": 32,
					"snowballsHit": 0,
					"soloBaronKills": 0,
					"soloKills": 1,
					"stealthWardsPlaced": 1,
					"survivedSingleDigitHpCount": 0,
					"survivedThreeImmobilizesInFight": 0,
					"takedownOnFirstTurret": 0,
					"takedowns": 32,
					"takedownsAfterGainingLevelAdvantage": 0,
					"takedownsBeforeJungleMinionSpawn": 0,
					"takedownsFirstXMinutes": 12,
					"takedownsInAlcove": 0,
					"takedownsInEnemyFountain": 0,
					"teamBaronKills": 2,
					"teamDamagePercentage": 0.20593002148460055,
					"teamElderDragonKills": 0,
					"teamRiftHeraldKills": 1,
					"threeWardsOneSweeperCount": 0,
					"tookLargeDamageSurvived": 0,
					"turretPlatesTaken": 0,
					"turretTakedowns": 3,
					"turretsTakenWithRiftHerald": 0,
					"twentyMinionsIn3SecondsCount": 0,
					"unseenRecalls": 0,
					"visionScoreAdvantageLaneOpponent": -0.07306128740310669,
					"visionScorePerMinute": 0.5253799438745428,
					"wardTakedowns": 5,
					"wardTakedownsBefore20M": 2,
					"wardsGuarded": 1
				},
				"champExperience": 17809,
				"champLevel": 17,
				"championId": 131,
				"championName": "Diana",
				"championTransform": 0,
				"consumablesPurchased": 0,
				"damageDealtToBuildings": 2479,
				"damageDealtToObjectives": 26209,
				"damageDealtToTurrets": 2479,
				"damageSelfMitigated": 44675,
				"deaths": 11,
				"detectorWardsPlaced": 0,
				"doubleKills": 1,
				"dragonKills": 1,
				"eligibleForProgression": true,
				"firstBloodAssist": false,
				"firstBloodKill": false,
				"firstTowerAssist": false,
				"firstTowerKill": false,
				"gameEndedInEarlySurrender": false,
				"gameEndedInSurrender": false,
				"goldEarned": 17588,
				"goldSpent": 14750,
				"individualPosition": "JUNGLE",
				"inhibitorKills": 0,
				"inhibitorTakedowns": 1,
				"inhibitorsLost": 1,
				"item0": 3152,
				"item1": 3157,
				"item2": 3115,
				"item3": 3020,
				"item4": 3089,
				"item5": 3145,
				"item6": 3364,
				"itemsPurchased": 24,
				"killingSprees": 4,
				"kills": 15,
				"lane": "JUNGLE",
				"largestCriticalStrike": 0,
				"largestKillingSpree": 3,
				"largestMultiKill": 2,
				"longestTimeSpentLiving": 373,
				"magicDamageDealt": 178820,
				"magicDamageDealtToChampions": 26736,
				"magicDamageTaken": 11550,
				"neutralMinionsKilled": 150,
				"nexusKills": 0,
				"nexusLost": 0,
				"nexusTakedowns": 1,
				"objectivesStolen": 1,
				"objectivesStolenAssists": 0,
				"participantId": 2,
				"pentaKills": 0,
				"perks": {
					"statPerks": {
						"defense": 5002,
						"flex": 5008,
						"offense": 5005
					},
					"styles": [
						{
							"description": "primaryStyle",
							"selections": [
								{
									"perk": 8010,
									"var1": 648,
									"var2": 0,
									"var3": 0
								},
								{
									"perk": 9111,
									"var1": 2750,
									"var2": 640,
									"var3": 0
								},
								{
									"perk": 9105,
									"var1": 10,
									"var2": 10,
									"var3": 0
								},
								{
									"perk": 8299,
									"var1": 1537,
									"var2": 0,
									"var3": 0
								}
							],
							"style": 8000
						},
						{
							"description": "subStyle",
							"selections": [
								{
									"perk": 8347,
									"var1": 0,
									"var2": 0,
									"var3": 0
								},
								{
									"perk": 8304,
									"var1": 8,
									"var2": 1,
									"var3": 5
								}
							],
							"style": 8300
						}
					]
				},
				"physicalDamageDealt": 25181,
				"physicalDamageDealtToChampions": 3728,
				"physicalDamageTaken": 29218,
				"profileIcon": 4930,
				"puuid": "CmvZCVRjJ2iAK9DeRWlPHU4DVSkvppQ29kc4G8QzXUqPAst8Md1KUJiWB9xxxyaXdosKqrEzQz6N7Q",
				"quadraKills": 0,
				"riotIdName": "",
				"riotIdTagline": "",
				"role": "NONE",
				"sightWardsBoughtInGame": 0,
				"spell1Casts": 115,
				"spell2Casts": 61,
				"spell3Casts": 62,
				"spell4Casts": 13,
				"summoner1Casts": 6,
				"summoner1Id": 4,
				"summoner2Casts": 20,
				"summoner2Id": 11,
				"summonerId": "SkKgJZA_djaWTvp9Od3qTVbg6bSJLI9ygPYradz-TFI_8n2PjqxFo2BW8Q",
				"summonerLevel": 165,
				"summonerName": "15 jg diff",
				"teamEarlySurrendered": false,
				"teamId": 100,
				"teamPosition": "JUNGLE",
				"timeCCingOthers": 16,
				"timePlayed": 2134,
				"totalDamageDealt": 219579,
				"totalDamageDealtToChampions": 32622,
				"totalDamageShieldedOnTeammates": 0,
				"totalDamageTaken": 41709,
				"totalHeal": 10234,
				"totalHealsOnTeammates": 0,
				"totalMinionsKilled": 40,
				"totalTimeCCDealt": 238,
				"totalTimeSpentDead": 407,
				"totalUnitsHealed": 1,
				"tripleKills": 0,
				"trueDamageDealt": 15577,
				"trueDamageDealtToChampions": 2157,
				"trueDamageTaken": 941,
				"turretKills": 1,
				"turretTakedowns": 3,
				"turretsLost": 7,
				"unrealKills": 0,
				"visionScore": 18,
				"visionWardsBoughtInGame": 0,
				"wardsKilled": 5,
				"wardsPlaced": 1,
				"win": true
			},
			{
				"assists": 20,
				"baronKills": 1,
				"basicPings": 20,
				"bountyLevel": 5,
				"challenges": {
					"12AssistStreakCount": 0,
					"abilityUses": 396,
					"acesBefore15Minutes": 0,
					"alliedJungleMonsterKills": 0.4000000059604645,
					"baronBuffGoldAdvantageOverThreshold": 1,
					"baronTakedowns": 1,
					"blastConeOppositeOpponentCount": 0,
					"bountyGold": 675,
					"buffsStolen": 0,
					"completeSupportQuestInTime": 0,
					"controlWardTimeCoverageInRiverOrEnemyHalf": 0.035856371787534265,
					"controlWardsPlaced": 1,
					"damagePerMinute": 1285.0861266640811,
					"damageTakenOnTeamPercentage": 0.2763497238190687,
					"dancedWithRiftHerald": 0,
					"deathsByEnemyChamps": 4,
					"dodgeSkillShotsSmallWindow": 4,
					"doubleAces": 0,
					"dragonTakedowns": 2,
					"earliestBaron": 1695.1561379032444,
					"earliestDragonTakedown": 1256.163291947661,
					"earlyLaningPhaseGoldExpAdvantage": 0,
					"effectiveHealAndShielding": 0,
					"elderDragonKillsWithOpposingSoul": 0,
					"elderDragonMultikills": 0,
					"enemyChampionImmobilizations": 0,
					"enemyJungleMonsterKills": 0,
					"epicMonsterKillsNearEnemyJungler": 0,
					"epicMonsterKillsWithin30SecondsOfSpawn": 0,
					"epicMonsterSteals": 0,
					"epicMonsterStolenWithoutSmite": 0,
					"fastestLegendary": 1400.163496848556,
					"firstTurretKilledTime": 663.4359872877812,
					"flawlessAces": 1,
					"fullTeamTakedown": 7,
					"gameLength": 2134.5152520014904,
					"getTakedownsInAllLanesEarlyJungleAsLaner": 0,
					"goldPerMinute": 499.1097725237787,
					"hadOpenNexus": 0,
					"immobilizeAndKillWithAlly": 0,
					"initialBuffCount": 0,
					"initialCrabCount": 0,
					"jungleCsBefore10Minutes": 0,
					"junglerTakedownsNearDamagedEpicMonster": 1,
					"kTurretsDestroyedBeforePlatesFall": 0,
					"kda": 9.5,
					"killAfterHiddenWithAlly": 0,
					"killParticipation": 0.6551724137931034,
					"killedChampTookFullTeamDamageSurvived": 0,
					"killingSprees": 3,
					"killsNearEnemyTurret": 4,
					"killsOnOtherLanesEarlyJungleAsLaner": 0,
					"killsOnRecentlyHealedByAramPack": 0,
					"killsUnderOwnTurret": 4,
					"killsWithHelpFromEpicMonster": 0,
					"knockEnemyIntoTeamAndKill": 0,
					"landSkillShotsEarlyGame": 0,
					"laneMinionsFirst10Minutes": 69,
					"laningPhaseGoldExpAdvantage": 0,
					"legendaryCount": 1,
					"lostAnInhibitor": 1,
					"maxCsAdvantageOnLaneOpponent": 35,
					"maxKillDeficit": 3,
					"maxLevelLeadLaneOpponent": 3,
					"mejaisFullStackInTime": 1400.196516304637,
					"moreEnemyJungleThanOpponent": -132.00000008940697,
					"multiKillOneSpell": 0,
					"multiTurretRiftHeraldCount": 0,
					"multikills": 4,
					"multikillsAfterAggressiveFlash": 0,
					"mythicItemUsed": 3152,
					"outerTurretExecutesBefore10Minutes": 0,
					"outnumberedKills": 2,
					"outnumberedNexusKill": 0,
					"perfectDragonSoulsTaken": 0,
					"perfectGame": 0,
					"pickKillWithAlly": 22,
					"playedChampSelectPosition": 1,
					"poroExplosions": 0,
					"quickCleanse": 0,
					"quickFirstTurret": 0,
					"quickSoloKills": 0,
					"riftHeraldTakedowns": 1,
					"saveAllyFromDeath": 0,
					"scuttleCrabKills": 1,
					"shortestTimeToAceFromFirstTakedown": 6.659964493982216,
					"skillshotsDodged": 64,
					"skillshotsHit": 0,
					"snowballsHit": 0,
					"soloBaronKills": 0,
					"soloKills": 5,
					"stealthWardsPlaced": 12,
					"survivedSingleDigitHpCount": 0,
					"survivedThreeImmobilizesInFight": 0,
					"takedownOnFirstTurret": 0,
					"takedowns": 38,
					"takedownsAfterGainingLevelAdvantage": 0,
					"takedownsBeforeJungleMinionSpawn": 0,
					"takedownsFirstXMinutes": 9,
					"takedownsInAlcove": 0,
					"takedownsInEnemyFountain": 0,
					"teamBaronKills": 2,
					"teamDamagePercentage": 0.2885873497558363,
					"teamElderDragonKills": 0,
					"teamRiftHeraldKills": 1,
					"threeWardsOneSweeperCount": 0,
					"tookLargeDamageSurvived": 0,
					"turretPlatesTaken": 1,
					"turretTakedowns": 4,
					"turretsTakenWithRiftHerald": 0,
					"twentyMinionsIn3SecondsCount": 0,
					"unseenRecalls": 0,
					"visionScoreAdvantageLaneOpponent": 0.5514017343521118,
					"visionScorePerMinute": 0.7840496879006187,
					"wardTakedowns": 3,
					"wardTakedownsBefore20M": 0,
					"wardsGuarded": 0
				},
				"champExperience": 20173,
				"champLevel": 18,
				"championId": 8,
				"championName": "Vladimir",
				"championTransform": 0,
				"consumablesPurchased": 2,
				"damageDealtToBuildings": 3528,
				"damageDealtToObjectives": 23007,
				"damageDealtToTurrets": 3528,
				"damageSelfMitigated": 23159,
				"deaths": 4,
				"detectorWardsPlaced": 1,
				"doubleKills": 4,
				"dragonKills": 2,
				"eligibleForProgression": true,
				"firstBloodAssist": false,
				"firstBloodKill": false,
				"firstTowerAssist": false,
				"firstTowerKill": false,
				"gameEndedInEarlySurrender": false,
				"gameEndedInSurrender": false,
				"goldEarned": 17755,
				"goldSpent": 16025,
				"individualPosition": "MIDDLE",
				"inhibitorKills": 1,
				"inhibitorTakedowns": 1,
				"inhibitorsLost": 1,
				"item0": 3041,
				"item1": 3152,
				"item2": 3135,
				"item3": 4629,
				"item4": 3020,
				"item5": 3089,
				"item6": 3340,
				"itemsPurchased": 19,
				"killingSprees": 3,
				"kills": 18,
				"lane": "MIDDLE",
				"largestCriticalStrike": 0,
				"largestKillingSpree": 8,
				"largestMultiKill": 2,
				"longestTimeSpentLiving": 573,
				"magicDamageDealt": 154604,
				"magicDamageDealtToChampions": 42111,
				"magicDamageTaken": 16086,
				"neutralMinionsKilled": 16,
				"nexusKills": 0,
				"nexusLost": 0,
				"nexusTakedowns": 1,
				"objectivesStolen": 0,
				"objectivesStolenAssists": 0,
				"participantId": 3,
				"pentaKills": 0,
				"perks": {
					"statPerks": {
						"defense": 5001,
						"flex": 5008,
						"offense": 5007
					},
					"styles": [
						{
							"description": "primaryStyle",
							"selections": [
								{
									"perk": 8010,
									"var1": 450,
									"var2": 0,
									"var3": 0
								},
								{
									"perk": 9111,
									"var1": 4796,
									"var2": 760,
									"var3": 0
								},
								{
									"perk": 9105,
									"var1": 12,
									"var2": 0,
									"var3": 0
								},
								{
									"perk": 8299,
									"var1": 2647,
									"var2": 0,
									"var3": 0
								}
							],
							"style": 8000
						},
						{
							"description": "subStyle",
							"selections": [
								{
									"perk": 8210,
									"var1": 46,
									"var2": 0,
									"var3": 0
								},
								{
									"perk": 8275,
									"var1": 14,
									"var2": 0,
									"var3": 0
								}
							],
							"style": 8200
						}
					]
				},
				"physicalDamageDealt": 14144,
				"physicalDamageDealtToChampions": 1108,
				"physicalDamageTaken": 33298,
				"profileIcon": 5212,
				"puuid": "Q2EHjVk2eZKAl5XuGy_cWSMCIm7lLMW2OOzZqNxOF53NrU0hmeXOMfp6fRoSOiYYX1R3mmVF52X5BQ",
				"quadraKills": 0,
				"riotIdName": "",
				"riotIdTagline": "",
				"role": "SOLO",
				"sightWardsBoughtInGame": 0,
				"spell1Casts": 280,
				"spell2Casts": 19,
				"spell3Casts": 83,
				"spell4Casts": 14,
				"summoner1Casts": 8,
				"summoner1Id": 6,
				"summoner2Casts": 6,
				"summoner2Id": 14,
				"summonerId": "GPe5ul3KJRHMyLeunnYUzfLQ8U5nNXSFq8OZpIvkHvGDviYj4YVHROtilA",
				"summonerLevel": 64,
				"summonerName": "Now You Know",
				"teamEarlySurrendered": false,
				"teamId": 100,
				"teamPosition": "MIDDLE",
				"timeCCingOthers": 5,
				"timePlayed": 2134,
				"totalDamageDealt": 173379,
				"totalDamageDealtToChampions": 45717,
				"totalDamageShieldedOnTeammates": 0,
				"totalDamageTaken": 51406,
				"totalHeal": 47125,
				"totalHealsOnTeammates": 0,
				"totalMinionsKilled": 168,
				"totalTimeCCDealt": 94,
				"totalTimeSpentDead": 146,
				"totalUnitsHealed": 1,
				"tripleKills": 0,
				"trueDamageDealt": 4631,
				"trueDamageDealtToChampions": 2497,
				"trueDamageTaken": 2020,
				"turretKills": 2,
				"turretTakedowns": 4,
				"turretsLost": 7,
				"unrealKills": 0,
				"visionScore": 27,
				"visionWardsBoughtInGame": 1,
				"wardsKilled": 3,
				"wardsPlaced": 13,
				"win": true
			},
			{
				"assists": 26,
				"baronKills": 0,
				"basicPings": 5,
				"bountyLevel": 1,
				"challenges": {
					"12AssistStreakCount": 0,
					"abilityUses": 272,
					"acesBefore15Minutes": 0,
					"alliedJungleMonsterKills": 0,
					"baronBuffGoldAdvantageOverThreshold": 1,
					"baronTakedowns": 3,
					"blastConeOppositeOpponentCount": 0,
					"bountyGold": 0,
					"buffsStolen": 0,
					"completeSupportQuestInTime": 0,
					"controlWardTimeCoverageInRiverOrEnemyHalf": 0.009269903782952555,
					"controlWardsPlaced": 5,
					"damagePerMinute": 551.3076053610126,
					"damageTakenOnTeamPercentage": 0.1439446135426198,
					"dancedWithRiftHerald": 0,
					"deathsByEnemyChamps": 11,
					"dodgeSkillShotsSmallWindow": 8,
					"doubleAces": 0,
					"dragonTakedowns": 1,
					"earliestBaron": 1695.1561379032444,
					"earliestDragonTakedown": 1256.163291947661,
					"earlyLaningPhaseGoldExpAdvantage": 0,
					"effectiveHealAndShielding": 6059.6455078125,
					"elderDragonKillsWithOpposingSoul": 0,
					"elderDragonMultikills": 0,
					"enemyChampionImmobilizations": 39,
					"enemyJungleMonsterKills": 0,
					"epicMonsterKillsNearEnemyJungler": 0,
					"epicMonsterKillsWithin30SecondsOfSpawn": 0,
					"epicMonsterSteals": 0,
					"epicMonsterStolenWithoutSmite": 0,
					"firstTurretKilledTime": 663.4359872877812,
					"flawlessAces": 1,
					"fullTeamTakedown": 7,
					"gameLength": 2134.5152520014904,
					"getTakedownsInAllLanesEarlyJungleAsLaner": 0,
					"goldPerMinute": 390.14953673339625,
					"hadOpenNexus": 0,
					"immobilizeAndKillWithAlly": 15,
					"initialBuffCount": 0,
					"initialCrabCount": 0,
					"jungleCsBefore10Minutes": 0,
					"junglerTakedownsNearDamagedEpicMonster": 0,
					"kTurretsDestroyedBeforePlatesFall": 0,
					"kda": 3,
					"killAfterHiddenWithAlly": 5,
					"killParticipation": 0.5689655172413793,
					"killedChampTookFullTeamDamageSurvived": 0,
					"killsNearEnemyTurret": 0,
					"killsOnOtherLanesEarlyJungleAsLaner": 0,
					"killsOnRecentlyHealedByAramPack": 0,
					"killsUnderOwnTurret": 1,
					"killsWithHelpFromEpicMonster": 1,
					"knockEnemyIntoTeamAndKill": 0,
					"landSkillShotsEarlyGame": 24,
					"laneMinionsFirst10Minutes": 49,
					"laningPhaseGoldExpAdvantage": 0,
					"legendaryCount": 0,
					"lostAnInhibitor": 1,
					"maxCsAdvantageOnLaneOpponent": 11,
					"maxKillDeficit": 3,
					"maxLevelLeadLaneOpponent": 2,
					"moreEnemyJungleThanOpponent": -132.00000008940697,
					"multiKillOneSpell": 0,
					"multiTurretRiftHeraldCount": 0,
					"multikills": 1,
					"multikillsAfterAggressiveFlash": 0,
					"mythicItemUsed": 6653,
					"outerTurretExecutesBefore10Minutes": 0,
					"outnumberedKills": 0,
					"outnumberedNexusKill": 0,
					"perfectDragonSoulsTaken": 0,
					"perfectGame": 0,
					"pickKillWithAlly": 23,
					"playedChampSelectPosition": 1,
					"poroExplosions": 0,
					"quickCleanse": 0,
					"quickFirstTurret": 0,
					"quickSoloKills": 0,
					"riftHeraldTakedowns": 0,
					"saveAllyFromDeath": 1,
					"scuttleCrabKills": 1,
					"shortestTimeToAceFromFirstTakedown": 6.659964493982216,
					"skillshotsDodged": 79,
					"skillshotsHit": 131,
					"snowballsHit": 0,
					"soloBaronKills": 0,
					"soloKills": 0,
					"stealthWardsPlaced": 8,
					"survivedSingleDigitHpCount": 0,
					"survivedThreeImmobilizesInFight": 0,
					"takedownOnFirstTurret": 0,
					"takedowns": 33,
					"takedownsAfterGainingLevelAdvantage": 0,
					"takedownsBeforeJungleMinionSpawn": 0,
					"takedownsFirstXMinutes": 8,
					"takedownsInAlcove": 0,
					"takedownsInEnemyFountain": 0,
					"teamBaronKills": 2,
					"teamDamagePercentage": 0.12380524342315902,
					"teamElderDragonKills": 0,
					"teamRiftHeraldKills": 1,
					"threeWardsOneSweeperCount": 0,
					"tookLargeDamageSurvived": 0,
					"turretPlatesTaken": 2,
					"turretTakedowns": 5,
					"turretsTakenWithRiftHerald": 0,
					"twentyMinionsIn3SecondsCount": 0,
					"unseenRecalls": 0,
					"visionScoreAdvantageLaneOpponent": 1.2665657997131348,
					"visionScorePerMinute": 0.8794603483574915,
					"wardTakedowns": 1,
					"wardTakedownsBefore20M": 1,
					"wardsGuarded": 0
				},
				"champExperience": 17479,
				"champLevel": 17,
				"championId": 147,
				"championName": "Seraphine",
				"championTransform": 0,
				"consumablesPurchased": 7,
				"damageDealtToBuildings": 1239,
				"damageDealtToObjectives": 7068,
				"damageDealtToTurrets": 1239,
				"damageSelfMitigated": 14430,
				"deaths": 11,
				"detectorWardsPlaced": 5,
				"doubleKills": 1,
				"dragonKills": 0,
				"eligibleForProgression": true,
				"firstBloodAssist": false,
				"firstBloodKill": false,
				"firstTowerAssist": false,
				"firstTowerKill": false,
				"gameEndedInEarlySurrender": false,
				"gameEndedInSurrender": false,
				"goldEarned": 13879,
				"goldSpent": 12575,
				"individualPosition": "BOTTOM",
				"inhibitorKills": 0,
				"inhibitorTakedowns": 1,
				"inhibitorsLost": 1,
				"item0": 3040,
				"item1": 0,
				"item2": 3116,
				"item3": 6653,
				"item4": 3011,
				"item5": 3020,
				"item6": 3363,
				"itemsPurchased": 31,
				"killingSprees": 2,
				"kills": 7,
				"lane": "BOTTOM",
				"largestCriticalStrike": 0,
				"largestKillingSpree": 2,
				"largestMultiKill": 2,
				"longestTimeSpentLiving": 323,
				"magicDamageDealt": 114670,
				"magicDamageDealtToChampions": 17250,
				"magicDamageTaken": 3174,
				"neutralMinionsKilled": 4,
				"nexusKills": 1,
				"nexusLost": 0,
				"nexusTakedowns": 1,
				"objectivesStolen": 0,
				"objectivesStolenAssists": 1,
				"participantId": 4,
				"pentaKills": 0,
				"perks": {
					"statPerks": {
						"defense": 5002,
						"flex": 5008,
						"offense": 5008
					},
					"styles": [
						{
							"description": "primaryStyle",
							"selections": [
								{
									"perk": 8214,
									"var1": 1284,
									"var2": 470,
									"var3": 0
								},
								{
									"perk": 8226,
									"var1": 250,
									"var2": 982,
									"var3": 0
								},
								{
									"perk": 8210,
									"var1": 45,
									"var2": 0,
									"var3": 0
								},
								{
									"perk": 8236,
									"var1": 48,
									"var2": 0,
									"var3": 0
								}
							],
							"style": 8200
						},
						{
							"description": "subStyle",
							"selections": [
								{
									"perk": 8345,
									"var1": 3,
									"var2": 0,
									"var3": 0
								},
								{
									"perk": 8347,
									"var1": 0,
									"var2": 0,
									"var3": 0
								}
							],
							"style": 8300
						}
					]
				},
				"physicalDamageDealt": 12033,
				"physicalDamageDealtToChampions": 1897,
				"physicalDamageTaken": 22006,
				"profileIcon": 4070,
				"puuid": "-rDTCsroAW3qIMgqJRusRss1Al7Hp5anU4D3dwGhldx5yZ4wLzfkAi2D1ZbvXQqayEpEnsnhJjaKZA",
				"quadraKills": 0,
				"riotIdName": "",
				"riotIdTagline": "",
				"role": "CARRY",
				"sightWardsBoughtInGame": 0,
				"spell1Casts": 132,
				"spell2Casts": 46,
				"spell3Casts": 79,
				"spell4Casts": 15,
				"summoner1Casts": 7,
				"summoner1Id": 7,
				"summoner2Casts": 3,
				"summoner2Id": 4,
				"summonerId": "0fXFiaOib5OeQYDfUFplmv9uq8Nvx5BqI_RhnlXFxjxmQlA",
				"summonerLevel": 620,
				"summonerName": "Sønny",
				"teamEarlySurrendered": false,
				"teamId": 100,
				"teamPosition": "BOTTOM",
				"timeCCingOthers": 45,
				"timePlayed": 2134,
				"totalDamageDealt": 127686,
				"totalDamageDealtToChampions": 19612,
				"totalDamageShieldedOnTeammates": 3075,
				"totalDamageTaken": 26776,
				"totalHeal": 6067,
				"totalHealsOnTeammates": 2983,
				"totalMinionsKilled": 160,
				"totalTimeCCDealt": 249,
				"totalTimeSpentDead": 358,
				"totalUnitsHealed": 5,
				"tripleKills": 0,
				"trueDamageDealt": 982,
				"trueDamageDealtToChampions": 464,
				"trueDamageTaken": 1595,
				"turretKills": 2,
				"turretTakedowns": 5,
				"turretsLost": 7,
				"unrealKills": 0,
				"visionScore": 31,
				"visionWardsBoughtInGame": 5,
				"wardsKilled": 1,
				"wardsPlaced": 16,
				"win": true
			},
			{
				"assists": 31,
				"baronKills": 0,
				"basicPings": 17,
				"bountyLevel": 1,
				"challenges": {
					"12AssistStreakCount": 1,
					"abilityUses": 164,
					"acesBefore15Minutes": 0,
					"alliedJungleMonsterKills": 5.5,
					"baronBuffGoldAdvantageOverThreshold": 1,
					"baronTakedowns": 2,
					"blastConeOppositeOpponentCount": 0,
					"bountyGold": 150,
					"buffsStolen": 0,
					"completeSupportQuestInTime": 1,
					"controlWardTimeCoverageInRiverOrEnemyHalf": 0.13885760540037975,
					"controlWardsPlaced": 5,
					"damagePerMinute": 591.675157745192,
					"damageTakenOnTeamPercentage": 0.12746915756657717,
					"dancedWithRiftHerald": 0,
					"deathsByEnemyChamps": 13,
					"dodgeSkillShotsSmallWindow": 3,
					"doubleAces": 0,
					"dragonTakedowns": 3,
					"earliestBaron": 1695.1561379032444,
					"earliestDragonTakedown": 929.0467466755875,
					"earlyLaningPhaseGoldExpAdvantage": 0,
					"effectiveHealAndShielding": 9004.9033203125,
					"elderDragonKillsWithOpposingSoul": 0,
					"elderDragonMultikills": 0,
					"enemyChampionImmobilizations": 25,
					"enemyJungleMonsterKills": 0,
					"epicMonsterKillsNearEnemyJungler": 0,
					"epicMonsterKillsWithin30SecondsOfSpawn": 0,
					"epicMonsterSteals": 0,
					"epicMonsterStolenWithoutSmite": 0,
					"fasterSupportQuestCompletion": 1,
					"firstTurretKilledTime": 663.4359872877812,
					"flawlessAces": 1,
					"fullTeamTakedown": 7,
					"gameLength": 2134.5152520014904,
					"getTakedownsInAllLanesEarlyJungleAsLaner": 0,
					"goldPerMinute": 385.73965081612596,
					"hadOpenNexus": 0,
					"highestWardKills": 1,
					"immobilizeAndKillWithAlly": 7,
					"initialBuffCount": 0,
					"initialCrabCount": 0,
					"jungleCsBefore10Minutes": 0,
					"junglerTakedownsNearDamagedEpicMonster": 0,
					"kTurretsDestroyedBeforePlatesFall": 0,
					"kda": 2.8461538461538463,
					"killAfterHiddenWithAlly": 3,
					"killParticipation": 0.6379310344827587,
					"killedChampTookFullTeamDamageSurvived": 0,
					"killsNearEnemyTurret": 0,
					"killsOnOtherLanesEarlyJungleAsLaner": 0,
					"killsOnRecentlyHealedByAramPack": 0,
					"killsUnderOwnTurret": 0,
					"killsWithHelpFromEpicMonster": 0,
					"knockEnemyIntoTeamAndKill": 0,
					"landSkillShotsEarlyGame": 2,
					"laneMinionsFirst10Minutes": 4,
					"laningPhaseGoldExpAdvantage": 0,
					"legendaryCount": 0,
					"lostAnInhibitor": 1,
					"maxCsAdvantageOnLaneOpponent": 30,
					"maxKillDeficit": 3,
					"maxLevelLeadLaneOpponent": 2,
					"moreEnemyJungleThanOpponent": -132.00000008940697,
					"multiKillOneSpell": 0,
					"multiTurretRiftHeraldCount": 0,
					"multikills": 0,
					"multikillsAfterAggressiveFlash": 0,
					"mythicItemUsed": 6692,
					"outerTurretExecutesBefore10Minutes": 0,
					"outnumberedKills": 1,
					"outnumberedNexusKill": 0,
					"perfectDragonSoulsTaken": 0,
					"perfectGame": 0,
					"pickKillWithAlly": 25,
					"playedChampSelectPosition": 1,
					"poroExplosions": 0,
					"quickCleanse": 0,
					"quickFirstTurret": 0,
					"quickSoloKills": 0,
					"riftHeraldTakedowns": 0,
					"saveAllyFromDeath": 0,
					"scuttleCrabKills": 1,
					"shortestTimeToAceFromFirstTakedown": 6.659964493982216,
					"skillshotsDodged": 49,
					"skillshotsHit": 27,
					"snowballsHit": 0,
					"soloBaronKills": 0,
					"soloKills": 0,
					"stealthWardsPlaced": 19,
					"survivedSingleDigitHpCount": 0,
					"survivedThreeImmobilizesInFight": 0,
					"takedownOnFirstTurret": 0,
					"takedowns": 37,
					"takedownsAfterGainingLevelAdvantage": 0,
					"takedownsBeforeJungleMinionSpawn": 0,
					"takedownsFirstXMinutes": 10,
					"takedownsInAlcove": 0,
					"takedownsInEnemyFountain": 0,
					"teamBaronKills": 2,
					"teamDamagePercentage": 0.13287044513763166,
					"teamElderDragonKills": 0,
					"teamRiftHeraldKills": 1,
					"threeWardsOneSweeperCount": 2,
					"tookLargeDamageSurvived": 0,
					"turretPlatesTaken": 2,
					"turretTakedowns": 4,
					"turretsTakenWithRiftHerald": 0,
					"twentyMinionsIn3SecondsCount": 0,
					"unseenRecalls": 0,
					"visionScoreAdvantageLaneOpponent": 0.38987231254577637,
					"visionScorePerMinute": 2.8300639506247154,
					"wardTakedowns": 30,
					"wardTakedownsBefore20M": 10,
					"wardsGuarded": 0
				},
				"champExperience": 17368,
				"champLevel": 17,
				"championId": 235,
				"championName": "Senna",
				"championTransform": 0,
				"consumablesPurchased": 8,
				"damageDealtToBuildings": 3568,
				"damageDealtToObjectives": 16781,
				"damageDealtToTurrets": 3568,
				"damageSelfMitigated": 11301,
				"deaths": 13,
				"detectorWardsPlaced": 5,
				"doubleKills": 0,
				"dragonKills": 0,
				"eligibleForProgression": true,
				"firstBloodAssist": false,
				"firstBloodKill": false,
				"firstTowerAssist": false,
				"firstTowerKill": false,
				"gameEndedInEarlySurrender": false,
				"gameEndedInSurrender": false,
				"goldEarned": 13722,
				"goldSpent": 11025,
				"individualPosition": "UTILITY",
				"inhibitorKills": 0,
				"inhibitorTakedowns": 1,
				"inhibitorsLost": 1,
				"item0": 3864,
				"item1": 3094,
				"item2": 1038,
				"item3": 6692,
				"item4": 3179,
				"item5": 3009,
				"item6": 3364,
				"itemsPurchased": 32,
				"killingSprees": 1,
				"kills": 6,
				"lane": "BOTTOM",
				"largestCriticalStrike": 553,
				"largestKillingSpree": 2,
				"largestMultiKill": 1,
				"longestTimeSpentLiving": 324,
				"magicDamageDealt": 1814,
				"magicDamageDealtToChampions": 394,
				"magicDamageTaken": 7937,
				"neutralMinionsKilled": 12,
				"nexusKills": 0,
				"nexusLost": 0,
				"nexusTakedowns": 1,
				"objectivesStolen": 0,
				"objectivesStolenAssists": 0,
				"participantId": 5,
				"pentaKills": 0,
				"perks": {
					"statPerks": {
						"defense": 5003,
						"flex": 5008,
						"offense": 5005
					},
					"styles": [
						{
							"description": "primaryStyle",
							"selections": [
								{
									"perk": 8008,
									"var1": 27,
									"var2": 0,
									"var3": 0
								},
								{
									"perk": 8009,
									"var1": 3253,
									"var2": 0,
									"var3": 0
								},
								{
									"perk": 9104,
									"var1": 14,
									"var2": 30,
									"var3": 0
								},
								{
									"perk": 8017,
									"var1": 1917,
									"var2": 0,
									"var3": 0
								}
							],
							"style": 8000
						},
						{
							"description": "subStyle",
							"selections": [
								{
									"perk": 8345,
									"var1": 3,
									"var2": 0,
									"var3": 0
								},
								{
									"perk": 8410,
									"var1": 63,
									"var2": 0,
									"var3": 0
								}
							],
							"style": 8300
						}
					]
				},
				"physicalDamageDealt": 69766,
				"physicalDamageDealtToChampions": 19405,
				"physicalDamageTaken": 15276,
				"profileIcon": 5429,
				"puuid": "D-RPIY7vKgxySENc4fSfN7KfBO82gAbK_zDNQ_K9JiEA89KBgHNJ1Hs0MV3TN_Ns1CTmJoUtbGgUQA",
				"quadraKills": 0,
				"riotIdName": "",
				"riotIdTagline": "",
				"role": "SUPPORT",
				"sightWardsBoughtInGame": 0,
				"spell1Casts": 72,
				"spell2Casts": 53,
				"spell3Casts": 31,
				"spell4Casts": 8,
				"summoner1Casts": 7,
				"summoner1Id": 3,
				"summoner2Casts": 6,
				"summoner2Id": 4,
				"summonerId": "YzMLtHWH6Q5NbvQx-Ks0zLlBAj_OndiN-sn5BcyJxQCCIyk",
				"summonerLevel": 532,
				"summonerName": "CrazyCandy",
				"teamEarlySurrendered": false,
				"teamId": 100,
				"teamPosition": "UTILITY",
				"timeCCingOthers": 36,
				"timePlayed": 2134,
				"totalDamageDealt": 73968,
				"totalDamageDealtToChampions": 21048,
				"totalDamageShieldedOnTeammates": 2642,
				"totalDamageTaken": 23711,
				"totalHeal": 12031,
				"totalHealsOnTeammates": 6362,
				"totalMinionsKilled": 54,
				"totalTimeCCDealt": 229,
				"totalTimeSpentDead": 339,
				"totalUnitsHealed": 5,
				"tripleKills": 0,
				"trueDamageDealt": 2387,
				"trueDamageDealtToChampions": 1249,
				"trueDamageTaken": 498,
				"turretKills": 0,
				"turretTakedowns": 4,
				"turretsLost": 7,
				"unrealKills": 0,
				"visionScore": 100,
				"visionWardsBoughtInGame": 5,
				"wardsKilled": 30,
				"wardsPlaced": 24,
				"win": true
			},
			{
				"assists": 7,
				"baronKills": 0,
				"basicPings": 17,
				"bountyLevel": 0,
				"challenges": {
					"12AssistStreakCount": 0,
					"abilityUses": 294,
					"acesBefore15Minutes": 0,
					"alliedJungleMonsterKills": 1.5,
					"baronTakedowns": 0,
					"blastConeOppositeOpponentCount": 0,
					"bountyGold": 750,
					"buffsStolen": 1,
					"completeSupportQuestInTime": 0,
					"controlWardTimeCoverageInRiverOrEnemyHalf": 0.019292748865861582,
					"controlWardsPlaced": 1,
					"damagePerMinute": 926.1166695325257,
					"damageTakenOnTeamPercentage": 0.24235719852607318,
					"dancedWithRiftHerald": 0,
					"deathsByEnemyChamps": 9,
					"dodgeSkillShotsSmallWindow": 0,
					"doubleAces": 0,
					"dragonTakedowns": 1,
					"earliestDragonTakedown": 1610.1348217476261,
					"earlyLaningPhaseGoldExpAdvantage": 0,
					"effectiveHealAndShielding": 0,
					"elderDragonKillsWithOpposingSoul": 0,
					"elderDragonMultikills": 0,
					"enemyChampionImmobilizations": 22,
					"enemyJungleMonsterKills": 16,
					"epicMonsterKillsNearEnemyJungler": 0,
					"epicMonsterKillsWithin30SecondsOfSpawn": 0,
					"epicMonsterSteals": 0,
					"epicMonsterStolenWithoutSmite": 0,
					"flawlessAces": 0,
					"fullTeamTakedown": 1,
					"gameLength": 2134.5152520014904,
					"getTakedownsInAllLanesEarlyJungleAsLaner": 0,
					"goldPerMinute": 478.05389038831174,
					"hadOpenNexus": 0,
					"immobilizeAndKillWithAlly": 7,
					"initialBuffCount": 0,
					"initialCrabCount": 0,
					"jungleCsBefore10Minutes": 0,
					"junglerTakedownsNearDamagedEpicMonster": 0,
					"kTurretsDestroyedBeforePlatesFall": 0,
					"kda": 2.111111111111111,
					"killAfterHiddenWithAlly": 1,
					"killParticipation": 0.40425531914893614,
					"killedChampTookFullTeamDamageSurvived": 0,
					"killingSprees": 2,
					"killsNearEnemyTurret": 2,
					"killsOnOtherLanesEarlyJungleAsLaner": 0,
					"killsOnRecentlyHealedByAramPack": 0,
					"killsUnderOwnTurret": 3,
					"killsWithHelpFromEpicMonster": 2,
					"knockEnemyIntoTeamAndKill": 10,
					"landSkillShotsEarlyGame": 0,
					"laneMinionsFirst10Minutes": 70,
					"laningPhaseGoldExpAdvantage": 0,
					"legendaryCount": 0,
					"lostAnInhibitor": 0,
					"maxCsAdvantageOnLaneOpponent": 20.999999970197678,
					"maxKillDeficit": 0,
					"maxLevelLeadLaneOpponent": 2,
					"moreEnemyJungleThanOpponent": -122.00000008940697,
					"multiKillOneSpell": 0,
					"multiTurretRiftHeraldCount": 1,
					"multikills": 3,
					"multikillsAfterAggressiveFlash": 1,
					"mythicItemUsed": 3078,
					"outerTurretExecutesBefore10Minutes": 0,
					"outnumberedKills": 1,
					"outnumberedNexusKill": 0,
					"perfectDragonSoulsTaken": 0,
					"perfectGame": 0,
					"pickKillWithAlly": 15,
					"playedChampSelectPosition": 1,
					"poroExplosions": 0,
					"quickCleanse": 0,
					"quickFirstTurret": 0,
					"quickSoloKills": 0,
					"riftHeraldTakedowns": 1,
					"saveAllyFromDeath": 0,
					"scuttleCrabKills": 0,
					"shortestTimeToAceFromFirstTakedown": 39.241234499380425,
					"skillshotsDodged": 19,
					"skillshotsHit": 0,
					"snowballsHit": 0,
					"soloBaronKills": 0,
					"soloKills": 3,
					"stealthWardsPlaced": 11,
					"survivedSingleDigitHpCount": 1,
					"survivedThreeImmobilizesInFight": 13,
					"takedownOnFirstTurret": 0,
					"takedowns": 19,
					"takedownsAfterGainingLevelAdvantage": 0,
					"takedownsBeforeJungleMinionSpawn": 0,
					"takedownsFirstXMinutes": 5,
					"takedownsInAlcove": 0,
					"takedownsInEnemyFountain": 0,
					"teamBaronKills": 0,
					"teamDamagePercentage": 0.20342721993602625,
					"teamElderDragonKills": 0,
					"teamRiftHeraldKills": 1,
					"threeWardsOneSweeperCount": 0,
					"tookLargeDamageSurvived": 1,
					"turretPlatesTaken": 0,
					"turretTakedowns": 4,
					"turretsTakenWithRiftHerald": 10,
					"twentyMinionsIn3SecondsCount": 0,
					"unseenRecalls": 0,
					"visionScoreAdvantageLaneOpponent": -0.20832562446594238,
					"visionScorePerMinute": 0.4165032302169679,
					"wardTakedowns": 2,
					"wardTakedownsBefore20M": 0,
					"wardsGuarded": 0
				},
				"champExperience": 18858,
				"champLevel": 18,
				"championId": 122,
				"championName": "Darius",
				"championTransform": 0,
				"consumablesPurchased": 4,
				"damageDealtToBuildings": 3173,
				"damageDealtToObjectives": 19163,
				"damageDealtToTurrets": 3173,
				"damageSelfMitigated": 76856,
				"deaths": 9,
				"detectorWardsPlaced": 1,
				"doubleKills": 2,
				"dragonKills": 1,
				"eligibleForProgression": true,
				"firstBloodAssist": false,
				"firstBloodKill": false,
				"firstTowerAssist": false,
				"firstTowerKill": false,
				"gameEndedInEarlySurrender": false,
				"gameEndedInSurrender": false,
				"goldEarned": 17006,
				"goldSpent": 15883,
				"individualPosition": "TOP",
				"inhibitorKills": 1,
				"inhibitorTakedowns": 1,
				"inhibitorsLost": 1,
				"item0": 6333,
				"item1": 3078,
				"item2": 3111,
				"item3": 4401,
				"item4": 3075,
				"item5": 3211,
				"item6": 3340,
				"itemsPurchased": 29,
				"killingSprees": 4,
				"kills": 12,
				"lane": "TOP",
				"largestCriticalStrike": 22,
				"largestKillingSpree": 4,
				"largestMultiKill": 3,
				"longestTimeSpentLiving": 580,
				"magicDamageDealt": 5311,
				"magicDamageDealtToChampions": 1047,
				"magicDamageTaken": 13569,
				"neutralMinionsKilled": 24,
				"nexusKills": 0,
				"nexusLost": 1,
				"nexusTakedowns": 0,
				"objectivesStolen": 0,
				"objectivesStolenAssists": 0,
				"participantId": 6,
				"pentaKills": 0,
				"perks": {
					"statPerks": {
						"defense": 5003,
						"flex": 5008,
						"offense": 5005
					},
					"styles": [
						{
							"description": "primaryStyle",
							"selections": [
								{
									"perk": 8010,
									"var1": 782,
									"var2": 0,
									"var3": 0
								},
								{
									"perk": 9111,
									"var1": 2129,
									"var2": 380,
									"var3": 0
								},
								{
									"perk": 9103,
									"var1": 20,
									"var2": 50,
									"var3": 0
								},
								{
									"perk": 8299,
									"var1": 1544,
									"var2": 0,
									"var3": 0
								}
							],
							"style": 8000
						},
						{
							"description": "subStyle",
							"selections": [
								{
									"perk": 8473,
									"var1": 1154,
									"var2": 0,
									"var3": 0
								},
								{
									"perk": 8242,
									"var1": 141,
									"var2": 0,
									"var3": 0
								}
							],
							"style": 8400
						}
					]
				},
				"physicalDamageDealt": 195714,
				"physicalDamageDealtToChampions": 25831,
				"physicalDamageTaken": 23014,
				"profileIcon": 5091,
				"puuid": "bEi2StPDZEKf-uUqTicfkuUaSAs0HtHN-XCicQO8YfQGkOMl0pW3QRS6lZNUtCxOOwziKHtfhFc1JQ",
				"quadraKills": 0,
				"riotIdName": "",
				"riotIdTagline": "",
				"role": "SOLO",
				"sightWardsBoughtInGame": 0,
				"spell1Casts": 109,
				"spell2Casts": 138,
				"spell3Casts": 27,
				"spell4Casts": 20,
				"summoner1Casts": 8,
				"summoner1Id": 6,
				"summoner2Casts": 5,
				"summoner2Id": 4,
				"summonerId": "RcCRE7DE3p5tyIRFiv6WNSCpny-eVEDkYkZdXuNBKd48pC6Y",
				"summonerLevel": 71,
				"summonerName": "AzzCheeks",
				"teamEarlySurrendered": false,
				"teamId": 200,
				"teamPosition": "TOP",
				"timeCCingOthers": 28,
				"timePlayed": 2134,
				"totalDamageDealt": 222989,
				"totalDamageDealtToChampions": 32946,
				"totalDamageShieldedOnTeammates": 0,
				"totalDamageTaken": 46654,
				"totalHeal": 11390,
				"totalHealsOnTeammates": 0,
				"totalMinionsKilled": 233,
				"totalTimeCCDealt": 189,
				"totalTimeSpentDead": 274,
				"totalUnitsHealed": 1,
				"tripleKills": 1,
				"trueDamageDealt": 21963,
				"trueDamageDealtToChampions": 6068,
				"trueDamageTaken": 10071,
				"turretKills": 4,
				"turretTakedowns": 4,
				"turretsLost": 7,
				"unrealKills": 0,
				"visionScore": 14,
				"visionWardsBoughtInGame": 2,
				"wardsKilled": 2,
				"wardsPlaced": 12,
				"win": false
			},
			{
				"assists": 11,
				"baronKills": 0,
				"basicPings": 55,
				"bountyLevel": 0,
				"challenges": {
					"12AssistStreakCount": 0,
					"abilityUses": 777,
					"acesBefore15Minutes": 0,
					"alliedJungleMonsterKills": 115.50000014901161,
					"baronTakedowns": 0,
					"blastConeOppositeOpponentCount": 0,
					"bountyGold": 0,
					"buffsStolen": 1,
					"completeSupportQuestInTime": 0,
					"controlWardTimeCoverageInRiverOrEnemyHalf": 0.03804820355203174,
					"controlWardsPlaced": 3,
					"damagePerMinute": 907.1916686045063,
					"damageTakenOnTeamPercentage": 0.22061040222605222,
					"dancedWithRiftHerald": 0,
					"deathsByEnemyChamps": 11,
					"dodgeSkillShotsSmallWindow": 0,
					"doubleAces": 0,
					"dragonTakedowns": 1,
					"earliestDragonTakedown": 549.8694093228007,
					"earlyLaningPhaseGoldExpAdvantage": 0,
					"effectiveHealAndShielding": 0,
					"elderDragonKillsWithOpposingSoul": 0,
					"elderDragonMultikills": 0,
					"enemyChampionImmobilizations": 9,
					"enemyJungleMonsterKills": 24.5,
					"epicMonsterKillsNearEnemyJungler": 0,
					"epicMonsterKillsWithin30SecondsOfSpawn": 0,
					"epicMonsterSteals": 0,
					"epicMonsterStolenWithoutSmite": 0,
					"flawlessAces": 0,
					"fullTeamTakedown": 1,
					"gameLength": 2134.5152520014904,
					"goldPerMinute": 354.02601366875706,
					"hadOpenNexus": 0,
					"immobilizeAndKillWithAlly": 7,
					"initialBuffCount": 2,
					"initialCrabCount": 1,
					"jungleCsBefore10Minutes": 67.00000008940697,
					"junglerKillsEarlyJungle": 0,
					"junglerTakedownsNearDamagedEpicMonster": 1,
					"kTurretsDestroyedBeforePlatesFall": 0,
					"kda": 1.5454545454545454,
					"killAfterHiddenWithAlly": 1,
					"killParticipation": 0.3617021276595745,
					"killedChampTookFullTeamDamageSurvived": 0,
					"killsNearEnemyTurret": 1,
					"killsOnLanersEarlyJungleAsJungler": 1,
					"killsOnRecentlyHealedByAramPack": 0,
					"killsUnderOwnTurret": 0,
					"killsWithHelpFromEpicMonster": 0,
					"knockEnemyIntoTeamAndKill": 0,
					"landSkillShotsEarlyGame": 3,
					"laneMinionsFirst10Minutes": 0,
					"laningPhaseGoldExpAdvantage": 0,
					"legendaryCount": 0,
					"lostAnInhibitor": 0,
					"maxCsAdvantageOnLaneOpponent": 25.999999910593033,
					"maxKillDeficit": 0,
					"maxLevelLeadLaneOpponent": 1,
					"moreEnemyJungleThanOpponent": -55,
					"multiKillOneSpell": 0,
					"multiTurretRiftHeraldCount": 1,
					"multikills": 0,
					"multikillsAfterAggressiveFlash": 0,
					"mythicItemUsed": 3152,
					"outerTurretExecutesBefore10Minutes": 0,
					"outnumberedKills": 2,
					"outnumberedNexusKill": 0,
					"perfectDragonSoulsTaken": 0,
					"perfectGame": 0,
					"pickKillWithAlly": 13,
					"playedChampSelectPosition": 1,
					"poroExplosions": 0,
					"quickCleanse": 0,
					"quickFirstTurret": 0,
					"quickSoloKills": 1,
					"riftHeraldTakedowns": 1,
					"saveAllyFromDeath": 0,
					"scuttleCrabKills": 2,
					"shortestTimeToAceFromFirstTakedown": 39.241234499380425,
					"skillshotsDodged": 34,
					"skillshotsHit": 36,
					"snowballsHit": 0,
					"soloBaronKills": 0,
					"soloKills": 2,
					"stealthWardsPlaced": 11,
					"survivedSingleDigitHpCount": 0,
					"survivedThreeImmobilizesInFight": 0,
					"takedownOnFirstTurret": 0,
					"takedowns": 17,
					"takedownsAfterGainingLevelAdvantage": 0,
					"takedownsBeforeJungleMinionSpawn": 0,
					"takedownsFirstXMinutes": 5,
					"takedownsInAlcove": 0,
					"takedownsInEnemyFountain": 0,
					"teamBaronKills": 0,
					"teamDamagePercentage": 0.1992702271372496,
					"teamElderDragonKills": 0,
					"teamRiftHeraldKills": 1,
					"threeWardsOneSweeperCount": 0,
					"tookLargeDamageSurvived": 0,
					"turretPlatesTaken": 0,
					"turretTakedowns": 0,
					"turretsTakenWithRiftHerald": 10,
					"twentyMinionsIn3SecondsCount": 0,
					"unseenRecalls": 0,
					"visionScoreAdvantageLaneOpponent": 0.07881999015808105,
					"visionScorePerMinute": 0.5667903716015467,
					"wardTakedowns": 0,
					"wardTakedownsBefore20M": 0,
					"wardsGuarded": 1
				},
				"champExperience": 16893,
				"champLevel": 17,
				"championId": 28,
				"championName": "Evelynn",
				"championTransform": 0,
				"consumablesPurchased": 4,
				"damageDealtToBuildings": 0,
				"damageDealtToObjectives": 16401,
				"damageDealtToTurrets": 0,
				"damageSelfMitigated": 18504,
				"deaths": 11,
				"detectorWardsPlaced": 3,
				"doubleKills": 0,
				"dragonKills": 1,
				"eligibleForProgression": true,
				"firstBloodAssist": false,
				"firstBloodKill": false,
				"firstTowerAssist": false,
				"firstTowerKill": false,
				"gameEndedInEarlySurrender": false,
				"gameEndedInSurrender": false,
				"goldEarned": 12594,
				"goldSpent": 13115,
				"individualPosition": "JUNGLE",
				"inhibitorKills": 0,
				"inhibitorTakedowns": 0,
				"inhibitorsLost": 1,
				"item0": 3020,
				"item1": 3152,
				"item2": 3089,
				"item3": 3100,
				"item4": 1052,
				"item5": 2055,
				"item6": 3340,
				"itemsPurchased": 27,
				"killingSprees": 0,
				"kills": 6,
				"lane": "JUNGLE",
				"largestCriticalStrike": 0,
				"largestKillingSpree": 0,
				"largestMultiKill": 1,
				"longestTimeSpentLiving": 348,
				"magicDamageDealt": 174360,
				"magicDamageDealtToChampions": 30312,
				"magicDamageTaken": 18101,
				"neutralMinionsKilled": 171,
				"nexusKills": 0,
				"nexusLost": 1,
				"nexusTakedowns": 0,
				"objectivesStolen": 0,
				"objectivesStolenAssists": 0,
				"participantId": 7,
				"pentaKills": 0,
				"perks": {
					"statPerks": {
						"defense": 5001,
						"flex": 5008,
						"offense": 5008
					},
					"styles": [
						{
							"description": "primaryStyle",
							"selections": [
								{
									"perk": 8112,
									"var1": 2855,
									"var2": 0,
									"var3": 0
								},
								{
									"perk": 8143,
									"var1": 1874,
									"var2": 0,
									"var3": 0
								},
								{
									"perk": 8138,
									"var1": 30,
									"var2": 0,
									"var3": 0
								},
								{
									"perk": 8105,
									"var1": 11,
									"var2": 4,
									"var3": 0
								}
							],
							"style": 8100
						},
						{
							"description": "subStyle",
							"selections": [
								{
									"perk": 8233,
									"var1": 20,
									"var2": 10,
									"var3": 0
								},
								{
									"perk": 8236,
									"var1": 48,
									"var2": 0,
									"var3": 0
								}
							],
							"style": 8200
						}
					]
				},
				"physicalDamageDealt": 16530,
				"physicalDamageDealtToChampions": 605,
				"physicalDamageTaken": 19575,
				"profileIcon": 3231,
				"puuid": "FOp274IqCSUu86Wxe3UXmxIH3DpihuXsFzFJJUoYfSEM7GzAPt3Lbxo8H1Lwi2E_zAFwGVKnkcd2_Q",
				"quadraKills": 0,
				"riotIdName": "",
				"riotIdTagline": "",
				"role": "NONE",
				"sightWardsBoughtInGame": 0,
				"spell1Casts": 595,
				"spell2Casts": 32,
				"spell3Casts": 138,
				"spell4Casts": 12,
				"summoner1Casts": 16,
				"summoner1Id": 11,
				"summoner2Casts": 4,
				"summoner2Id": 4,
				"summonerId": "KQVXv54NeSvNRT4zneeLvWyuhU57xhlPy0v4k2LsSMpsy0w",
				"summonerLevel": 85,
				"summonerName": "Noyano",
				"teamEarlySurrendered": false,
				"teamId": 200,
				"teamPosition": "JUNGLE",
				"timeCCingOthers": 11,
				"timePlayed": 2134,
				"totalDamageDealt": 201119,
				"totalDamageDealtToChampions": 32273,
				"totalDamageShieldedOnTeammates": 0,
				"totalDamageTaken": 42468,
				"totalHeal": 10290,
				"totalHealsOnTeammates": 0,
				"totalMinionsKilled": 23,
				"totalTimeCCDealt": 192,
				"totalTimeSpentDead": 373,
				"totalUnitsHealed": 1,
				"tripleKills": 0,
				"trueDamageDealt": 10229,
				"trueDamageDealtToChampions": 1355,
				"trueDamageTaken": 4791,
				"turretKills": 0,
				"turretTakedowns": 0,
				"turretsLost": 7,
				"unrealKills": 0,
				"visionScore": 20,
				"visionWardsBoughtInGame": 4,
				"wardsKilled": 0,
				"wardsPlaced": 14,
				"win": false
			},
			{
				"assists": 10,
				"baronKills": 0,
				"basicPings": 38,
				"bountyLevel": 0,
				"challenges": {
					"12AssistStreakCount": 0,
					"abilityUses": 275,
					"acesBefore15Minutes": 0,
					"alliedJungleMonsterKills": 24.000000089406967,
					"baronTakedowns": 0,
					"blastConeOppositeOpponentCount": 0,
					"bountyGold": 1050,
					"buffsStolen": 0,
					"completeSupportQuestInTime": 0,
					"controlWardsPlaced": 0,
					"damagePerMinute": 1736.6613214166962,
					"damageTakenOnTeamPercentage": 0.223110202149528,
					"dancedWithRiftHerald": 0,
					"deathsByEnemyChamps": 14,
					"dodgeSkillShotsSmallWindow": 2,
					"doubleAces": 0,
					"dragonTakedowns": 2,
					"earliestDragonTakedown": 549.8694093228007,
					"earlyLaningPhaseGoldExpAdvantage": 0,
					"effectiveHealAndShielding": 0,
					"elderDragonKillsWithOpposingSoul": 0,
					"elderDragonMultikills": 0,
					"enemyChampionImmobilizations": 18,
					"enemyJungleMonsterKills": 0,
					"epicMonsterKillsNearEnemyJungler": 0,
					"epicMonsterKillsWithin30SecondsOfSpawn": 0,
					"epicMonsterSteals": 0,
					"epicMonsterStolenWithoutSmite": 0,
					"flawlessAces": 0,
					"fullTeamTakedown": 1,
					"gameLength": 2134.5152520014904,
					"getTakedownsInAllLanesEarlyJungleAsLaner": 0,
					"goldPerMinute": 502.82845203078017,
					"hadOpenNexus": 0,
					"highestChampionDamage": 1,
					"immobilizeAndKillWithAlly": 3,
					"initialBuffCount": 0,
					"initialCrabCount": 0,
					"jungleCsBefore10Minutes": 0,
					"junglerTakedownsNearDamagedEpicMonster": 0,
					"kTurretsDestroyedBeforePlatesFall": 0,
					"kda": 2.2142857142857144,
					"killAfterHiddenWithAlly": 1,
					"killParticipation": 0.6595744680851063,
					"killedChampTookFullTeamDamageSurvived": 0,
					"killingSprees": 3,
					"killsNearEnemyTurret": 6,
					"killsOnOtherLanesEarlyJungleAsLaner": 3,
					"killsOnRecentlyHealedByAramPack": 0,
					"killsUnderOwnTurret": 0,
					"killsWithHelpFromEpicMonster": 1,
					"knockEnemyIntoTeamAndKill": 0,
					"landSkillShotsEarlyGame": 6,
					"laneMinionsFirst10Minutes": 54,
					"laningPhaseGoldExpAdvantage": 0,
					"legendaryCount": 0,
					"lostAnInhibitor": 0,
					"maxCsAdvantageOnLaneOpponent": 0,
					"maxKillDeficit": 0,
					"maxLevelLeadLaneOpponent": 0,
					"moreEnemyJungleThanOpponent": -122.00000008940697,
					"multiKillOneSpell": 0,
					"multiTurretRiftHeraldCount": 1,
					"multikills": 6,
					"multikillsAfterAggressiveFlash": 3,
					"mythicItemUsed": 6673,
					"outerTurretExecutesBefore10Minutes": 0,
					"outnumberedKills": 10,
					"outnumberedNexusKill": 0,
					"perfectDragonSoulsTaken": 0,
					"perfectGame": 0,
					"pickKillWithAlly": 23,
					"playedChampSelectPosition": 1,
					"poroExplosions": 0,
					"quickCleanse": 0,
					"quickFirstTurret": 0,
					"quickSoloKills": 1,
					"riftHeraldTakedowns": 0,
					"saveAllyFromDeath": 0,
					"scuttleCrabKills": 0,
					"shortestTimeToAceFromFirstTakedown": 39.241234499380425,
					"skillshotsDodged": 32,
					"skillshotsHit": 64,
					"snowballsHit": 0,
					"soloBaronKills": 0,
					"soloKills": 6,
					"stealthWardsPlaced": 11,
					"survivedSingleDigitHpCount": 0,
					"survivedThreeImmobilizesInFight": 2,
					"takedownOnFirstTurret": 0,
					"takedowns": 31,
					"takedownsAfterGainingLevelAdvantage": 1,
					"takedownsBeforeJungleMinionSpawn": 0,
					"takedownsFirstXMinutes": 12,
					"takedownsInAlcove": 1,
					"takedownsInEnemyFountain": 0,
					"teamBaronKills": 0,
					"teamDamagePercentage": 0.38146833569527566,
					"teamElderDragonKills": 0,
					"teamRiftHeraldKills": 1,
					"threeWardsOneSweeperCount": 0,
					"tookLargeDamageSurvived": 0,
					"turretPlatesTaken": 0,
					"turretTakedowns": 1,
					"turretsTakenWithRiftHerald": 10,
					"twentyMinionsIn3SecondsCount": 0,
					"unseenRecalls": 0,
					"visionScoreAdvantageLaneOpponent": -0.35542160272598267,
					"visionScorePerMinute": 0.505381476041199,
					"wardTakedowns": 3,
					"wardTakedownsBefore20M": 0,
					"wardsGuarded": 0
				},
				"champExperience": 14549,
				"champLevel": 15,
				"championId": 360,
				"championName": "Samira",
				"championTransform": 0,
				"consumablesPurchased": 0,
				"damageDealtToBuildings": 1427,
				"damageDealtToObjectives": 21887,
				"damageDealtToTurrets": 1427,
				"damageSelfMitigated": 30421,
				"deaths": 14,
				"detectorWardsPlaced": 0,
				"doubleKills": 4,
				"dragonKills": 0,
				"eligibleForProgression": true,
				"firstBloodAssist": false,
				"firstBloodKill": false,
				"firstTowerAssist": false,
				"firstTowerKill": false,
				"gameEndedInEarlySurrender": false,
				"gameEndedInSurrender": false,
				"goldEarned": 17888,
				"goldSpent": 17450,
				"individualPosition": "MIDDLE",
				"inhibitorKills": 0,
				"inhibitorTakedowns": 0,
				"inhibitorsLost": 1,
				"item0": 6676,
				"item1": 3072,
				"item2": 6673,
				"item3": 3111,
				"item4": 3031,
				"item5": 3036,
				"item6": 3340,
				"itemsPurchased": 25,
				"killingSprees": 6,
				"kills": 21,
				"lane": "MIDDLE",
				"largestCriticalStrike": 850,
				"largestKillingSpree": 4,
				"largestMultiKill": 3,
				"longestTimeSpentLiving": 295,
				"magicDamageDealt": 17725,
				"magicDamageDealtToChampions": 6959,
				"magicDamageTaken": 23808,
				"neutralMinionsKilled": 24,
				"nexusKills": 0,
				"nexusLost": 1,
				"nexusTakedowns": 0,
				"objectivesStolen": 0,
				"objectivesStolenAssists": 0,
				"participantId": 8,
				"pentaKills": 0,
				"perks": {
					"statPerks": {
						"defense": 5003,
						"flex": 5008,
						"offense": 5005
					},
					"styles": [
						{
							"description": "primaryStyle",
							"selections": [
								{
									"perk": 8010,
									"var1": 825,
									"var2": 0,
									"var3": 0
								},
								{
									"perk": 9111,
									"var1": 1552,
									"var2": 620,
									"var3": 0
								},
								{
									"perk": 9103,
									"var1": 14,
									"var2": 20,
									"var3": 0
								},
								{
									"perk": 8299,
									"var1": 2310,
									"var2": 0,
									"var3": 0
								}
							],
							"style": 8000
						},
						{
							"description": "subStyle",
							"selections": [
								{
									"perk": 8139,
									"var1": 1361,
									"var2": 0,
									"var3": 0
								},
								{
									"perk": 8135,
									"var1": 550,
									"var2": 5,
									"var3": 0
								}
							],
							"style": 8100
						}
					]
				},
				"physicalDamageDealt": 172113,
				"physicalDamageDealtToChampions": 52975,
				"physicalDamageTaken": 17540,
				"profileIcon": 5269,
				"puuid": "5gNuzOZXrH-LyqWmwtInxbuExHZv_WNBwPEs8GGf7Huf2JKlLT8J8IPB0PxI1TGOMRF-FDu52hrp5w",
				"quadraKills": 0,
				"riotIdName": "",
				"riotIdTagline": "",
				"role": "SOLO",
				"sightWardsBoughtInGame": 0,
				"spell1Casts": 193,
				"spell2Casts": 27,
				"spell3Casts": 40,
				"spell4Casts": 15,
				"summoner1Casts": 5,
				"summoner1Id": 4,
				"summoner2Casts": 7,
				"summoner2Id": 14,
				"summonerId": "Kcth8UgoogxhVVVdGIZqT22aQgMtavUPya5748jdDdijhjdB",
				"summonerLevel": 83,
				"summonerName": "TurtleSings",
				"teamEarlySurrendered": false,
				"teamId": 200,
				"teamPosition": "MIDDLE",
				"timeCCingOthers": 6,
				"timePlayed": 2134,
				"totalDamageDealt": 197227,
				"totalDamageDealtToChampions": 61782,
				"totalDamageShieldedOnTeammates": 0,
				"totalDamageTaken": 42949,
				"totalHeal": 3318,
				"totalHealsOnTeammates": 0,
				"totalMinionsKilled": 140,
				"totalTimeCCDealt": 56,
				"totalTimeSpentDead": 451,
				"totalUnitsHealed": 1,
				"tripleKills": 2,
				"trueDamageDealt": 7388,
				"trueDamageDealtToChampions": 1847,
				"trueDamageTaken": 1601,
				"turretKills": 1,
				"turretTakedowns": 1,
				"turretsLost": 7,
				"unrealKills": 0,
				"visionScore": 17,
				"visionWardsBoughtInGame": 0,
				"wardsKilled": 3,
				"wardsPlaced": 11,
				"win": false
			},
			{
				"assists": 13,
				"baronKills": 0,
				"basicPings": 26,
				"bountyLevel": 0,
				"challenges": {
					"12AssistStreakCount": 0,
					"abilityUses": 311,
					"acesBefore15Minutes": 0,
					"alliedJungleMonsterKills": 0,
					"baronTakedowns": 0,
					"blastConeOppositeOpponentCount": 0,
					"bountyGold": 150,
					"buffsStolen": 0,
					"completeSupportQuestInTime": 0,
					"controlWardsPlaced": 0,
					"damagePerMinute": 746.739602267029,
					"damageTakenOnTeamPercentage": 0.16942849378658906,
					"dancedWithRiftHerald": 0,
					"deathsByEnemyChamps": 15,
					"dodgeSkillShotsSmallWindow": 0,
					"doubleAces": 0,
					"dragonTakedowns": 0,
					"earlyLaningPhaseGoldExpAdvantage": 0,
					"effectiveHealAndShielding": 0,
					"elderDragonKillsWithOpposingSoul": 0,
					"elderDragonMultikills": 0,
					"enemyChampionImmobilizations": 16,
					"enemyJungleMonsterKills": 0,
					"epicMonsterKillsNearEnemyJungler": 0,
					"epicMonsterKillsWithin30SecondsOfSpawn": 0,
					"epicMonsterSteals": 0,
					"epicMonsterStolenWithoutSmite": 0,
					"flawlessAces": 0,
					"fullTeamTakedown": 1,
					"gameLength": 2134.5152520014904,
					"getTakedownsInAllLanesEarlyJungleAsLaner": 0,
					"goldPerMinute": 324.8562247358286,
					"hadOpenNexus": 0,
					"immobilizeAndKillWithAlly": 4,
					"initialBuffCount": 0,
					"initialCrabCount": 0,
					"jungleCsBefore10Minutes": 4,
					"junglerTakedownsNearDamagedEpicMonster": 0,
					"kTurretsDestroyedBeforePlatesFall": 0,
					"kda": 1.2,
					"killAfterHiddenWithAlly": 1,
					"killParticipation": 0.3829787234042553,
					"killedChampTookFullTeamDamageSurvived": 0,
					"killsNearEnemyTurret": 1,
					"killsOnOtherLanesEarlyJungleAsLaner": 0,
					"killsOnRecentlyHealedByAramPack": 0,
					"killsUnderOwnTurret": 2,
					"killsWithHelpFromEpicMonster": 1,
					"knockEnemyIntoTeamAndKill": 0,
					"landSkillShotsEarlyGame": 9,
					"laneMinionsFirst10Minutes": 55,
					"laningPhaseGoldExpAdvantage": 0,
					"legendaryCount": 0,
					"lostAnInhibitor": 0,
					"maxCsAdvantageOnLaneOpponent": 22,
					"maxKillDeficit": 0,
					"maxLevelLeadLaneOpponent": 2,
					"moreEnemyJungleThanOpponent": -118.00000008940697,
					"multiKillOneSpell": 0,
					"multiTurretRiftHeraldCount": 1,
					"multikills": 0,
					"multikillsAfterAggressiveFlash": 0,
					"mythicItemUsed": 6671,
					"outerTurretExecutesBefore10Minutes": 0,
					"outnumberedKills": 1,
					"outnumberedNexusKill": 0,
					"perfectDragonSoulsTaken": 0,
					"perfectGame": 0,
					"pickKillWithAlly": 16,
					"playedChampSelectPosition": 1,
					"poroExplosions": 0,
					"quickCleanse": 0,
					"quickFirstTurret": 0,
					"quickSoloKills": 0,
					"riftHeraldTakedowns": 0,
					"saveAllyFromDeath": 0,
					"scuttleCrabKills": 1,
					"skillshotsDodged": 40,
					"skillshotsHit": 72,
					"snowballsHit": 0,
					"soloBaronKills": 0,
					"soloKills": 2,
					"stealthWardsPlaced": 4,
					"survivedSingleDigitHpCount": 0,
					"survivedThreeImmobilizesInFight": 0,
					"takedownOnFirstTurret": 0,
					"takedowns": 18,
					"takedownsAfterGainingLevelAdvantage": 0,
					"takedownsBeforeJungleMinionSpawn": 0,
					"takedownsFirstXMinutes": 7,
					"takedownsInAlcove": 2,
					"takedownsInEnemyFountain": 0,
					"teamBaronKills": 0,
					"teamDamagePercentage": 0.16402594435752202,
					"teamElderDragonKills": 0,
					"teamRiftHeraldKills": 1,
					"threeWardsOneSweeperCount": 0,
					"tookLargeDamageSurvived": 0,
					"turretPlatesTaken": 2,
					"turretTakedowns": 2,
					"turretsTakenWithRiftHerald": 10,
					"twentyMinionsIn3SecondsCount": 0,
					"unseenRecalls": 0,
					"visionScoreAdvantageLaneOpponent": -0.558803915977478,
					"visionScorePerMinute": 0.38801448110280296,
					"wardTakedowns": 2,
					"wardTakedownsBefore20M": 0,
					"wardsGuarded": 0
				},
				"champExperience": 13592,
				"champLevel": 15,
				"championId": 523,
				"championName": "Aphelios",
				"championTransform": 0,
				"consumablesPurchased": 1,
				"damageDealtToBuildings": 5804,
				"damageDealtToObjectives": 7859,
				"damageDealtToTurrets": 5804,
				"damageSelfMitigated": 11385,
				"deaths": 15,
				"detectorWardsPlaced": 0,
				"doubleKills": 0,
				"dragonKills": 0,
				"eligibleForProgression": true,
				"firstBloodAssist": false,
				"firstBloodKill": false,
				"firstTowerAssist": false,
				"firstTowerKill": false,
				"gameEndedInEarlySurrender": false,
				"gameEndedInSurrender": false,
				"goldEarned": 11556,
				"goldSpent": 15050,
				"individualPosition": "BOTTOM",
				"inhibitorKills": 0,
				"inhibitorTakedowns": 0,
				"inhibitorsLost": 1,
				"item0": 6671,
				"item1": 3031,
				"item2": 3006,
				"item3": 3033,
				"item4": 2420,
				"item5": 0,
				"item6": 3363,
				"itemsPurchased": 24,
				"killingSprees": 1,
				"kills": 5,
				"lane": "JUNGLE",
				"largestCriticalStrike": 689,
				"largestKillingSpree": 2,
				"largestMultiKill": 1,
				"longestTimeSpentLiving": 224,
				"magicDamageDealt": 4572,
				"magicDamageDealtToChampions": 2678,
				"magicDamageTaken": 17948,
				"neutralMinionsKilled": 4,
				"nexusKills": 0,
				"nexusLost": 1,
				"nexusTakedowns": 0,
				"objectivesStolen": 0,
				"objectivesStolenAssists": 0,
				"participantId": 9,
				"pentaKills": 0,
				"perks": {
					"statPerks": {
						"defense": 5002,
						"flex": 5008,
						"offense": 5005
					},
					"styles": [
						{
							"description": "primaryStyle",
							"selections": [
								{
									"perk": 8021,
									"var1": 2296,
									"var2": 1834,
									"var3": 0
								},
								{
									"perk": 9111,
									"var1": 803,
									"var2": 360,
									"var3": 0
								},
								{
									"perk": 9103,
									"var1": 24,
									"var2": 20,
									"var3": 0
								},
								{
									"perk": 8017,
									"var1": 1906,
									"var2": 0,
									"var3": 0
								}
							],
							"style": 8000
						},
						{
							"description": "subStyle",
							"selections": [
								{
									"perk": 8401,
									"var1": 150,
									"var2": 0,
									"var3": 0
								},
								{
									"perk": 8453,
									"var1": 1023,
									"var2": 436,
									"var3": 0
								}
							],
							"style": 8400
						}
					]
				},
				"physicalDamageDealt": 114122,
				"physicalDamageDealtToChampions": 23160,
				"physicalDamageTaken": 13614,
				"profileIcon": 5435,
				"puuid": "HaRBje9KHYHSixzs9louvCODlRS0GsR0QChK2vChlTrbLVt-SEKC1Ksy3FhW6msgPco24YBmbxJqxw",
				"quadraKills": 0,
				"riotIdName": "",
				"riotIdTagline": "",
				"role": "NONE",
				"sightWardsBoughtInGame": 0,
				"spell1Casts": 105,
				"spell2Casts": 195,
				"spell3Casts": 0,
				"spell4Casts": 11,
				"summoner1Casts": 8,
				"summoner1Id": 6,
				"summoner2Casts": 4,
				"summoner2Id": 4,
				"summonerId": "LxX5R76anqiiD9zGBEJtd2Lzgg2IQUFWu6XAz6CaRE6L7ro",
				"summonerLevel": 369,
				"summonerName": "TiddyBongo",
				"teamEarlySurrendered": false,
				"teamId": 200,
				"teamPosition": "BOTTOM",
				"timeCCingOthers": 21,
				"timePlayed": 2134,
				"totalDamageDealt": 119421,
				"totalDamageDealtToChampions": 26565,
				"totalDamageShieldedOnTeammates": 0,
				"totalDamageTaken": 32615,
				"totalHeal": 5778,
				"totalHealsOnTeammates": 0,
				"totalMinionsKilled": 150,
				"totalTimeCCDealt": 98,
				"totalTimeSpentDead": 452,
				"totalUnitsHealed": 1,
				"tripleKills": 0,
				"trueDamageDealt": 726,
				"trueDamageDealtToChampions": 726,
				"trueDamageTaken": 1052,
				"turretKills": 1,
				"turretTakedowns": 2,
				"turretsLost": 7,
				"unrealKills": 0,
				"visionScore": 13,
				"visionWardsBoughtInGame": 0,
				"wardsKilled": 2,
				"wardsPlaced": 5,
				"win": false
			},
			{
				"assists": 25,
				"baronKills": 0,
				"basicPings": 8,
				"bountyLevel": 0,
				"challenges": {
					"12AssistStreakCount": 0,
					"abilityUses": 283,
					"acesBefore15Minutes": 0,
					"alliedJungleMonsterKills": 0,
					"baronTakedowns": 0,
					"blastConeOppositeOpponentCount": 0,
					"bountyGold": 750,
					"buffsStolen": 0,
					"completeSupportQuestInTime": 1,
					"controlWardTimeCoverageInRiverOrEnemyHalf": 0.12465363243103994,
					"controlWardsPlaced": 10,
					"damagePerMinute": 235.8607916055774,
					"damageTakenOnTeamPercentage": 0.14449370331175754,
					"dancedWithRiftHerald": 0,
					"deathsByEnemyChamps": 9,
					"dodgeSkillShotsSmallWindow": 1,
					"doubleAces": 0,
					"dragonTakedowns": 0,
					"earlyLaningPhaseGoldExpAdvantage": 0,
					"effectiveHealAndShielding": 9252.791015625,
					"elderDragonKillsWithOpposingSoul": 0,
					"elderDragonMultikills": 0,
					"enemyChampionImmobilizations": 9,
					"enemyJungleMonsterKills": 0,
					"epicMonsterKillsNearEnemyJungler": 0,
					"epicMonsterKillsWithin30SecondsOfSpawn": 0,
					"epicMonsterSteals": 0,
					"epicMonsterStolenWithoutSmite": 0,
					"flawlessAces": 0,
					"fullTeamTakedown": 1,
					"gameLength": 2134.5152520014904,
					"getTakedownsInAllLanesEarlyJungleAsLaner": 0,
					"goldPerMinute": 316.9149273866504,
					"hadOpenNexus": 0,
					"highestCrowdControlScore": 1,
					"immobilizeAndKillWithAlly": 4,
					"initialBuffCount": 0,
					"initialCrabCount": 0,
					"jungleCsBefore10Minutes": 0,
					"junglerTakedownsNearDamagedEpicMonster": 0,
					"kTurretsDestroyedBeforePlatesFall": 0,
					"kda": 3.111111111111111,
					"killAfterHiddenWithAlly": 1,
					"killParticipation": 0.5957446808510638,
					"killedChampTookFullTeamDamageSurvived": 0,
					"killsNearEnemyTurret": 0,
					"killsOnOtherLanesEarlyJungleAsLaner": 0,
					"killsOnRecentlyHealedByAramPack": 0,
					"killsUnderOwnTurret": 1,
					"killsWithHelpFromEpicMonster": 0,
					"knockEnemyIntoTeamAndKill": 0,
					"landSkillShotsEarlyGame": 42,
					"laneMinionsFirst10Minutes": 8,
					"laningPhaseGoldExpAdvantage": 0,
					"legendaryCount": 0,
					"lostAnInhibitor": 0,
					"maxCsAdvantageOnLaneOpponent": 9,
					"maxKillDeficit": 0,
					"maxLevelLeadLaneOpponent": 1,
					"moreEnemyJungleThanOpponent": -122.00000008940697,
					"multiKillOneSpell": 0,
					"multiTurretRiftHeraldCount": 1,
					"multikills": 0,
					"multikillsAfterAggressiveFlash": 0,
					"mythicItemUsed": 2065,
					"outerTurretExecutesBefore10Minutes": 0,
					"outnumberedKills": 0,
					"outnumberedNexusKill": 0,
					"perfectDragonSoulsTaken": 0,
					"perfectGame": 0,
					"pickKillWithAlly": 26,
					"playedChampSelectPosition": 1,
					"poroExplosions": 0,
					"quickCleanse": 0,
					"quickFirstTurret": 0,
					"quickSoloKills": 0,
					"riftHeraldTakedowns": 0,
					"saveAllyFromDeath": 2,
					"scuttleCrabKills": 0,
					"shortestTimeToAceFromFirstTakedown": 39.241234499380425,
					"skillshotsDodged": 26,
					"skillshotsHit": 125,
					"snowballsHit": 0,
					"soloBaronKills": 0,
					"soloKills": 0,
					"stealthWardsPlaced": 35,
					"survivedSingleDigitHpCount": 0,
					"survivedThreeImmobilizesInFight": 0,
					"takedownOnFirstTurret": 0,
					"takedowns": 28,
					"takedownsAfterGainingLevelAdvantage": 0,
					"takedownsBeforeJungleMinionSpawn": 0,
					"takedownsFirstXMinutes": 12,
					"takedownsInAlcove": 0,
					"takedownsInEnemyFountain": 0,
					"teamBaronKills": 0,
					"teamDamagePercentage": 0.05180827287392644,
					"teamElderDragonKills": 0,
					"teamRiftHeraldKills": 1,
					"threeWardsOneSweeperCount": 0,
					"tookLargeDamageSurvived": 0,
					"turretPlatesTaken": 2,
					"turretTakedowns": 2,
					"turretsTakenWithRiftHerald": 10,
					"twentyMinionsIn3SecondsCount": 0,
					"unseenRecalls": 0,
					"visionScoreAdvantageLaneOpponent": -0.28050947189331055,
					"visionScorePerMinute": 2.0362042611024815,
					"wardTakedowns": 8,
					"wardTakedownsBefore20M": 4,
					"wardsGuarded": 0
				},
				"champExperience": 13067,
				"champLevel": 15,
				"championId": 117,
				"championName": "Lulu",
				"championTransform": 0,
				"consumablesPurchased": 21,
				"damageDealtToBuildings": 987,
				"damageDealtToObjectives": 3673,
				"damageDealtToTurrets": 987,
				"damageSelfMitigated": 10477,
				"deaths": 9,
				"detectorWardsPlaced": 10,
				"doubleKills": 0,
				"dragonKills": 0,
				"eligibleForProgression": true,
				"firstBloodAssist": false,
				"firstBloodKill": false,
				"firstTowerAssist": false,
				"firstTowerKill": false,
				"gameEndedInEarlySurrender": false,
				"gameEndedInSurrender": false,
				"goldEarned": 11274,
				"goldSpent": 10725,
				"individualPosition": "UTILITY",
				"inhibitorKills": 0,
				"inhibitorTakedowns": 0,
				"inhibitorsLost": 1,
				"item0": 2055,
				"item1": 2065,
				"item2": 3853,
				"item3": 3504,
				"item4": 3011,
				"item5": 3117,
				"item6": 3364,
				"itemsPurchased": 36,
				"killingSprees": 1,
				"kills": 3,
				"lane": "BOTTOM",
				"largestCriticalStrike": 0,
				"largestKillingSpree": 2,
				"largestMultiKill": 1,
				"longestTimeSpentLiving": 368,
				"magicDamageDealt": 17401,
				"magicDamageDealtToChampions": 6851,
				"magicDamageTaken": 16383,
				"neutralMinionsKilled": 0,
				"nexusKills": 0,
				"nexusLost": 1,
				"nexusTakedowns": 0,
				"objectivesStolen": 0,
				"objectivesStolenAssists": 0,
				"participantId": 10,
				"pentaKills": 0,
				"perks": {
					"statPerks": {
						"defense": 5003,
						"flex": 5002,
						"offense": 5005
					},
					"styles": [
						{
							"description": "primaryStyle",
							"selections": [
								{
									"perk": 8214,
									"var1": 1072,
									"var2": 2304,
									"var3": 0
								},
								{
									"perk": 8275,
									"var1": 15,
									"var2": 0,
									"var3": 0
								},
								{
									"perk": 8210,
									"var1": 17,
									"var2": 0,
									"var3": 0
								},
								{
									"perk": 8236,
									"var1": 48,
									"var2": 0,
									"var3": 0
								}
							],
							"style": 8200
						},
						{
							"description": "subStyle",
							"selections": [
								{
									"perk": 8345,
									"var1": 3,
									"var2": 0,
									"var3": 0
								},
								{
									"perk": 8347,
									"var1": 0,
									"var2": 0,
									"var3": 0
								}
							],
							"style": 8300
						}
					]
				},
				"physicalDamageDealt": 4900,
				"physicalDamageDealtToChampions": 1346,
				"physicalDamageTaken": 9202,
				"profileIcon": 4510,
				"puuid": "jVJIG4Dp8Rj8om8zo5KzNOzvBqzB4BW4X5pj7Y-_wnSPz480YCN_E1HRRvBk4ZSTUrR7GIvuqnNIkw",
				"quadraKills": 0,
				"riotIdName": "",
				"riotIdTagline": "",
				"role": "SOLO",
				"sightWardsBoughtInGame": 0,
				"spell1Casts": 82,
				"spell2Casts": 75,
				"spell3Casts": 114,
				"spell4Casts": 12,
				"summoner1Casts": 7,
				"summoner1Id": 4,
				"summoner2Casts": 8,
				"summoner2Id": 7,
				"summonerId": "dP686rn2m1dy-1HzgD7gEK7mt0qnKg4dVyQg86tTXkWH2uQ",
				"summonerLevel": 297,
				"summonerName": "Jonnymoomoo",
				"teamEarlySurrendered": false,
				"teamId": 200,
				"teamPosition": "UTILITY",
				"timeCCingOthers": 38,
				"timePlayed": 2134,
				"totalDamageDealt": 30525,
				"totalDamageDealtToChampions": 8390,
				"totalDamageShieldedOnTeammates": 7634,
				"totalDamageTaken": 27815,
				"totalHeal": 4999,
				"totalHealsOnTeammates": 1618,
				"totalMinionsKilled": 36,
				"totalTimeCCDealt": 281,
				"totalTimeSpentDead": 253,
				"totalUnitsHealed": 5,
				"tripleKills": 0,
				"trueDamageDealt": 8222,
				"trueDamageDealtToChampions": 192,
				"trueDamageTaken": 2230,
				"turretKills": 0,
				"turretTakedowns": 2,
				"turretsLost": 7,
				"unrealKills": 0,
				"visionScore": 72,
				"visionWardsBoughtInGame": 11,
				"wardsKilled": 8,
				"wardsPlaced": 45,
				"win": false
			}
		],
		"platformId": "NA1",
		"queueId": 420,
		"teams": [
			{
				"bans": [
					{
						"championId": 11,
						"pickTurn": 1
					},
					{
						"championId": 350,
						"pickTurn": 2
					},
					{
						"championId": 15,
						"pickTurn": 3
					},
					{
						"championId": 54,
						"pickTurn": 4
					},
					{
						"championId": 777,
						"pickTurn": 5
					}
				],
				"objectives": {
					"baron": {
						"first": true,
						"kills": 2
					},
					"champion": {
						"first": true,
						"kills": 58
					},
					"dragon": {
						"first": false,
						"kills": 3
					},
					"inhibitor": {
						"first": false,
						"kills": 1
					},
					"riftHerald": {
						"first": true,
						"kills": 1
					},
					"tower": {
						"first": true,
						"kills": 7
					}
				},
				"teamId": 100,
				"win": true
			},
			{
				"bans": [
					{
						"championId": 157,
						"pickTurn": 6
					},
					{
						"championId": 266,
						"pickTurn": 7
					},
					{
						"championId": 111,
						"pickTurn": 8
					},
					{
						"championId": 141,
						"pickTurn": 9
					},
					{
						"championId": -1,
						"pickTurn": 10
					}
				],
				"objectives": {
					"baron": {
						"first": false,
						"kills": 0
					},
					"champion": {
						"first": false,
						"kills": 47
					},
					"dragon": {
						"first": true,
						"kills": 2
					},
					"inhibitor": {
						"first": true,
						"kills": 1
					},
					"riftHerald": {
						"first": false,
						"kills": 1
					},
					"tower": {
						"first": false,
						"kills": 7
					}
				},
				"teamId": 200,
				"win": false
			}
		],
		"tournamentCode": ""
	}
}

exports.timeline = {

}